[레벨2 글쓰기 미션] 배카라(박성우) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #124
Opened 2022-05-28 13:38 UTC by seong-wooo

[편하게 보기](https://github.com/seong-wooo/woowa-writing-4/blob/seong-wooo/Level2.md)

반갑습니다.

2022-05-28 14:30 UTC, HJ-Rich requested changes
배카라 안녕하세요~

멋진 글 너무 잘 읽었습니다.
불안감에 관련된 내용이 너무 공감됐고 배카라의 진정성이 잘 느껴졌네요.

몇 가지 간단한 의견 남겨보았어요. 참고부탁드릴게요 :)

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
> 스터디원들과 이해한 내용을 공유하다 보면 새롭게 알게 되는 것들이 많았다.

마자요마자요!! 저도 그래서 공부 해와서 서로 나누는 게 정말 효과적인 것 같아요! 👍

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
> 스터디원들에게 고마움을 느끼고, 더 가까워질 수 있었다.

👍👍👍

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
> 함께 자라는 시간과 혼자 자라는 시간을 잘 조절하여 더 만족스러운 기간을 보내야겠다.

완전 동의해요. 저 역시 `함께 자라는 시간을 더욱 효과적으로 만들기 위해서` 혼자서 준비하는 시간이 필요하다고 생각하는 편입니다!

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코에서 학습을 하면서 제일 많이 들었던 생각이다. 미션을 진행하면서 미션에 필요하지 않은 내용의 책들을 많이 읽었다. 미션과 개인 학습을 별개라고 생각했다. 책을 읽으면서 한번 보고 이해한 내용이 모두 내 지식이 되었다고 생각했다. 그래서 스스로 학습을 잘 하고 있다고 생각했다. 그러나 시간이 지날수록 스스로를 과대평가했다고 생각이 들었다. 조금만 시
> 책에서 학습한 내용을 미션에 적용했을 때는 쉽게 잊혀지지 않았다.

와 이거 정말 공감해요. 이론적으로 학습하고 이해한 내용을 미션 내에서 코드로 적용해보고 나면, 그때 비로소 나의 지식, 나의 실력이 되는 것 같아요! 😃

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 불안함을 느끼지 않았다. 그 당시 스스로의 상태에 대해 알지 못했기 때문이다. 우테코 기간 중, 불안함을 느낀 뒤로 열심히 달린 것 같다. 불안함은 미션 진행에 어려움을 느낄 때, 남들보다 뒤처진 느낌이 들 때 찾아왔다. 항상 잘할 수 있다는 자신감을 가지고 살았지만, 레벨 2부터는 이런 불안함을 가지게 되었다. 불안함을 이겨내기 위해 학
이 문단에서 배카라의 진심이 느껴져서 감동적이었어요.

불안함을 느끼게 되면 아무 행동도 하지 않게 되기 쉬운데,
이를 더욱 분발하게 되는 계기로 승화시킨 배카라에게 박수를 보내드리고 싶어요!! 대단해요 👏👏👏

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
> 함께 자라는 것에 대한 경험이 없었기 때문이다

이 문장을 조금 더 개선해볼 수 있을까요?
지금 이대로도 괜찮지만 다소 어색한 느낌이 들기도 해요.

한 편으론 함께 자라는 경험이 아주 없을 순 없는데요,
가령 고등학교까지 한 반으로 엮여서 같이 지내게 되고,
대학교를 가게 된다면 조별과제 등을 경험하게 되니까요.

그래서 함께 자라본 경험이 없다 라는 표현을 조금 더 풀어서 이야기해보면 어떨까 하는 생각이 들어요.
이전까지의 함께 자라기와 우테코에서의 함께 자라기가 어떻게 다르고 왜 달랐는지 궁금하기도 하네요.

음.. 말이 많았는데. 요약하자면
그냥 이 한 문장 혹시 개선해볼 수 있을까요? 😃

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
> 또한 책의 이해가 되지 않은 부분들을 스터디원들이 쉽게 설명해주었다.

이 문장은 이 앞의 내용들과는 약간 다른 맥락의 내용이 이어지는 것 같아요. 이 문장 앞에 개행을 해서 문단 구분을 해보면 어떨까요? 더불어 이 문장도 배카라가 더 멋진 문장으로 개선해볼 수 있을 것 같아요!

2022-05-28 14:30 UTC, HJ-Rich commented on Level2.md
> +### 경험해보기
이 문단에서 배카라가 전하고 싶은 내용은 `이론적으로 학습했던 내용을 실전에 적용해보는 경험을 통해 책으로 습득한 지식을 진정한 나의 지식으로 체득할 수 있었다` 라고 생각되는데 맞을까요?

만약 그렇다면 아래 문장의 연결을 조금 더 개선함으로써 독자에게 전달하고자 하는 바를 좀 더 명확히 할 수 있을 것 같다는 생각이 들어요. 더불어 경험해보기 라는 소제목도 조금 모호하다는 생각도 들긴 하지만, 다른 소제목과 통일감을 주기 위해서라면 괜찮다고 생각해요!

> 그래서 읽었던 내용을 반복해서 읽게 되었다. 어찌보면 반복해서 공부하는 것은 당연하다. 하지만 개발에 있어서는 달랐다. 

2022-05-29 21:03 UTC, summerlunaa reviewed
안녕하세요 배카라 글 보러 왔습니다.

저도 책만 읽으면 내용을 다 까먹은 편이라 경험이 중요하다는 부분이 공감됩니다~ 
개인적으로 저는 불안함을 많이 느끼지 않는 편인데 적당한 불안함이 배카라의 학습에는 도움이 되었군요. 앞으로도 적당한 불안감을 통해 꾸준히 성장할 수 있었으면 좋겠네요 응원합니다👍

2022-05-30 17:02 UTC, jaeyeonling reviewed
레벨1보다 더 성장한 모습이 보여서 좋네요!
잘 읽었습니다 :)

2022-06-04 09:14 UTC, rladpwl0512 commented
저랑 같이 짱먹은 배카라~ level1 글쓰기에 이어 level2 글쓰기에도 함께할 수 있어서 너무 반가워요 😊 
배카라의 공부 꿀팁도 잘 읽고갑니다 🍯 level2 동안 공부법에 대해 깊게 고민하신 흔적이 글에 느껴져서, 너무 좋았어요! 
몇가지 커멘트 남겼으니, 참고 부탁드려요 😊 (다만 제 의견이니 무조건 반영하지 않아도 되는거 알죠?!) 
좋은 글 잘읽었습니다~

2022-06-04 09:14 UTC, rladpwl0512 commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
`'처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?' 라는 생각을 하였다.` 와 같이, 생각부분은 작은 따옴표로 감싸주는 것은 어떨까요? 😊

2022-06-04 09:14 UTC, rladpwl0512 commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
배카라가 혼자자라기와 함께자라기에 대해 깊이 생각해보신 것이 느껴져서 너무 멋져요~! 👍

2022-06-04 09:14 UTC, rladpwl0512 commented on Level2.md
> +우테코에서 학습을 하면서 제일 많이 들었던 생각이다. 미션을 진행하면서 미션에 필요하지 않은 내용의 책들을 많이 읽었다. 미션과 개인 학습을 별개라고 생각했다. 책을 읽으면서 한번 보고 이해한 내용이 모두 내 지식이 되었다고 생각했다. 그래서 스스로 학습을 잘 하고 있다고 생각했다. 그러나 시간이 지날수록 스스로를 과대평가했다고 생각이 들었다. 조금만 시
`그러나 시간이 지날수록 스스로를 과대평가했다**는** 생각이 들었다.` 와 같이 바꿔주면 더 자연스럽게 읽힐 것 같습니다 😊

2022-06-04 09:14 UTC, rladpwl0512 commented on Level2.md
> +우테코 이전에는 불안함을 느끼지 않았다. 그 당시 스스로의 상태에 대해 알지 못했기 때문이다. 우테코 기간 중, 불안함을 느낀 뒤로 열심히 달린 것 같다. 불안함은 미션 진행에 어려움을 느낄 때, 남들보다 뒤처진 느낌이 들 때 찾아왔다. 항상 잘할 수 있다는 자신감을 가지고 살았지만, 레벨 2부터는 이런 불안함을 가지게 되었다. 불안함을 이겨내기 위해 학
위 커멘트와 마찬가지인데요, `이 과정에서 '불안함을 통해 성장하는 것이 우테코 취지에 맞는 것일까?' 라는 생각을 많이 했었다.` 와 같이 배카라의 생각을 작은 따옴표로 감싸주면 좋을 것 같아요 😄 

`불안함은 **우테코에서 찾은 나만의 효과적인 공부 실행법**이다.` 라는 표현 너무 멋지네요 👍 저도 불안함으로 성장할 수 있도록 노력해야겠어요

2022-06-05 11:11 UTC, Hongdonggeon approved these changes
글이 담백하고 배카라의 경험과 생각이 많이 담겨있어서 재미있게 읽었습니다. 저와 비슷한 생각을 많이 가지고 계신 것 같아요!! 글 작성하느라 너무 고생많으셨습니다!! 그리고 저도 배카라랑 페어 해보고 싶어요 ☺️

2022-06-05 11:11 UTC, Hongdonggeon commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
> 이러한 스터디원들의 도움을 통해 많은 성장을 이룰 수 있었다

개인적인 생각입니다!! 이러한 보다 '이렇게' 가 더 자연스럽다는 생각이 들어서요! 배카라 생각은 어떠신가요? 
추가적으로 그 다음 문장을 이어서 작성해도 될 것 같아요!!
`이렇게 스터디원들의 도움을 통해 많은 성장을 이루(면서 or 었고) 혼자 학습해도 충분하다라고 생각했던 과거의 모습을 반성하게 되었다.`

2022-06-06 04:54 UTC, seong-wooo commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
반영..해보았습니다.. !

2022-06-06 04:54 UTC, seong-wooo commented on Level2.md
> +우테코에서 학습을 하면서 제일 많이 들었던 생각이다. 미션을 진행하면서 미션에 필요하지 않은 내용의 책들을 많이 읽었다. 미션과 개인 학습을 별개라고 생각했다. 책을 읽으면서 한번 보고 이해한 내용이 모두 내 지식이 되었다고 생각했다. 그래서 스스로 학습을 잘 하고 있다고 생각했다. 그러나 시간이 지날수록 스스로를 과대평가했다고 생각이 들었다. 조금만 시
반영..해보았습니다.. !

2022-06-06 04:54 UTC, seong-wooo commented on Level2.md
> +우테코 이전에는 불안함을 느끼지 않았다. 그 당시 스스로의 상태에 대해 알지 못했기 때문이다. 우테코 기간 중, 불안함을 느낀 뒤로 열심히 달린 것 같다. 불안함은 미션 진행에 어려움을 느낄 때, 남들보다 뒤처진 느낌이 들 때 찾아왔다. 항상 잘할 수 있다는 자신감을 가지고 살았지만, 레벨 2부터는 이런 불안함을 가지게 되었다. 불안함을 이겨내기 위해 학
반영..해보았습니다.. !

2022-06-06 04:54 UTC, seong-wooo commented on Level2.md
> +### 경험해보기
반영..해보았습니다.. !

2022-06-06 05:12 UTC, nan-noo reviewed
경험이 잘 녹아든 글이어서 읽기 편했어요! 재밌게 읽었습니다ㅎㅎ

맞춤법 검사기 한 번 돌리면 더 좋을 것 같아요!

2022-06-06 05:12 UTC, nan-noo commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다.  다른 사람과 함께 학습하는 과정에서 함께 자란다는 느낌을 받은 적이 없었기 때문이다.우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. '처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?'라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의
편한 리뷰를 위해 마크다운에선 한줄마다 줄바꿈을 해주시면 좋을 것 같아요! 실제로는 붙어있는 것처럼 보입니다!
그리고 피동표현을 많이 쓰시는데, 능동표현으로 바꿔도 될 것 같습니다 :D 

```suggestion
우테코 이전에는 혼자 자라기를 매우 선호했다.  
다른 사람과 함께 학습하는 과정에서 함께 자란다는 느낌을 받은 적이 없었기 때문이다.
우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다.
처음에는 '같은 책을 읽는데, 서로 공유해야 할 것이 있을까?'라는 생각을 하였다. 
그러나 스터디를 진행하면서 생각이 조금씩 바뀌었다. 
스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책을 읽어도 습득하는 지식의 양이 달랐다. 
그래서 스터디원들과 이해한 내용을 공유하다 보면 새롭게 알게 되는 것들이 많았다. 
또한 스터디를 통해 책의 이해가 되지 않은 부분들을 스터디원들이 쉽게 설명해주었다. 
이렇게 스터디원들의 도움을 통해 많은 성장을 이루었고, **혼자 학습해도 충분하다**라고 생각했던 과거의 모습을 반성하였다. 
그리고 함께 자란 스터디원들에게 고마움을 느끼고, 더 가까워질 수 있었다. 
하지만 함께 자라는 것에 대한 단점도 존재하였다. 
함께 자라기를 진행하다 보니, 혼자 자라는 시간이 많이 줄어들었다. 
함께 자라는 시간의 중요성을 느꼈지만, 아직까지는 어느 정도의 혼자 자라는 시간도 중요하다고 생각한다. 
레벨 3에는 함께 자라는 시간과 혼자 자라는 시간을 잘 조절하여 더 만족스러운 기간을 보내야겠다.
```

2022-06-06 05:12 UTC, nan-noo commented on Level2.md
> +### 불안함 느끼기
오.. 굉장히 모순적인 제목인데 내용을 읽어보니 설득되네요..! 단순 불안이 아니군요 멋져요

2022-06-06 11:54 UTC, HJ-Rich commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다.  다른 사람과 함께 학습하는 과정에서 함께 자란다는 느낌을 받은 적이 없었기 때문이다.우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. '처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?'라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의
@nan-noo 동의합니다! ㅎㅎ

2022-06-06 11:55 UTC, HJ-Rich approved these changes
배카라~ 멋진 글 감사해요~!
가다듬으며 더욱 멋진글이 되었네요!

많은 대화를 나누지 못해 아쉬웠지만 글을 통해 배카라의 멋진 모습들 엿볼 수 있어서 너무 좋았습니다.

고생많으셨습니다.
남은 레벨2도 화이팅입니다! 😀

2022-06-07 00:24 UTC, jihyeok-um approved these changes
저도 배카라 같은 레벨2를 보냈으면 좀 더 의미가 있었을까? 하는 글이네요
함께 자라기와 불안감을 컨트롤하는 배카라의 모습이 멋있네요

2022-06-07 00:24 UTC, jihyeok-um commented on Level2.md
> +우테코 이전에는 혼자 자라기를 매우 선호했다. 함께 자라는 것에 대한 경험이 없었기 때문이다. 우테코를 기회로, 함께 자라기 경험을 위해 필독서 스터디를 진행했다. 처음에는 같은 책을 읽는데, 서로 공유해야 할 것이 있을까?라는 생각을 하였다. 그러나 스터디를 진행하면서 생각이 조금씩 바뀌게 되었다. 스터디원들의 사전 지식이 모두 다르기 때문에, 같은 책
아직도 혼자를 선호하는 저... 반성하게되네요 ㅎㅎㅎㅎㅎ ㅠ

2022-06-07 00:24 UTC, jihyeok-um commented on Level2.md
> +우테코 이전에는 불안함을 느끼지 않았다. 그 당시 스스로의 상태에 대해 알지 못했기 때문이다. 우테코 기간 중, 불안함을 느낀 뒤로 열심히 달린 것 같다. 불안함은 미션 진행에 어려움을 느낄 때, 남들보다 뒤처진 느낌이 들 때 찾아왔다. 항상 잘할 수 있다는 자신감을 가지고 살았지만, 레벨 2부터는 이런 불안함을 가지게 되었다. 불안함을 이겨내기 위해 학
덜불안감이라.. 어렵네요 저는 아직도 불안을 어떻게 컨트롤하는 건지 잘 모르겠습니다, 저는 그냥 불안감을 떨처내기 위해서는 (내가 보기에) 완벽한 플랜과 이행이 있어야만 했고, 아직도 그렇습니다!

2022-06-07 00:47 UTC, airman5573 reviewed
안녕하세요 배카라!  
공감되는 글 잘 읽었습니다 :D

2022-06-07 00:47 UTC, airman5573 commented on Level2.md
> +우테코에서 학습을 하면서 제일 많이 들었던 생각이다. 미션을 진행하면서 미션에 필요하지 않은 내용의 책들을 많이 읽었다. 미션과 개인 학습을 별개라고 생각했다. 책을 읽으면서 한번 보고 이해한 내용이 모두 내 지식이 되었다고 생각했다. 그래서 스스로 학습을 잘 하고 있다고 생각했다. 그러나 시간이 지날수록 스스로를 과대평가했다는 생각이 들었다. 조금만 시
확실히 직접 해보는게 기억에 오래 남더라구요!

2022-06-07 00:47 UTC, airman5573 commented on Level2.md
> +우테코에서 학습을 하면서 제일 많이 들었던 생각이다. 미션을 진행하면서 미션에 필요하지 않은 내용의 책들을 많이 읽었다. 미션과 개인 학습을 별개라고 생각했다. 책을 읽으면서 한번 보고 이해한 내용이 모두 내 지식이 되었다고 생각했다. 그래서 스스로 학습을 잘 하고 있다고 생각했다. 그러나 시간이 지날수록 스스로를 과대평가했다는 생각이 들었다. 조금만 시
`앞으로 효과적으로 성장하기 위해, 경험을 통해서 학습할 수 있다면, 반복하지 말고 직접 경험을 해볼 것이다.` 쉼표를 조금 줄여봐도 좋을것 같아요!

2022-06-07 02:33 UTC, airman5573 approved these changes

2022-06-07 02:58 UTC, nan-noo approved these changes

2022-06-07 07:00 UTC, rladpwl0512 approved these changes
배카라 수정된 글도 잘 읽었습니다~ 
다음에 보면 인사해요 🙋‍♀️

approve 하겠습니다. 남은 level2 기간도 알차게 보내세요 ✨

2022-08-04 01:06 UTC, merged