[레벨2 글쓰기 미션] 칙촉(안영윤) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #160
Opened 2022-05-29 17:26 UTC by Youngyoon-1

2022-05-30 01:23 UTC, her0807 approved these changes
안녕하세요 칙촉

지나가다 들린 수달입니다. 

글 내용을 보면서, 학습 방향에 대해 많은 고민들이 있었다는게 느껴지고,
그것을 이겨내고 있다는 점에서 대단하고 존경스럽습니다 !!!!✨
넘어졌을 때, 포기하지 않고 툭툭 털고 일어나 주어 고맙습니다.

칙촉의 기분좋은 에너지 덕분에 저 또한 즐겁게 달릴 용기를 얻고 있어요.👍🏻

글을 다 읽고 나니  `새로운 학습 방법을 찾은 지금, 촉촉의 느낌은 어떨까?` 라는 궁금증이 들더라구요
맨 마지막 단락에 이 부분은 추가해보면 어떨까요 ~?

2022-06-02 15:43 UTC, ulimy requested changes
안녕하세요 칙촉 아리입니다 :)
칙촉이 우테코 이전에 가지고있던 공부 방법과 이후에 바뀐 공부 방법이 드러나있어 재미있게 읽었습니다ㅎ
몇가지 남겨보았으니 확인 부탁드려요!

2022-06-02 15:43 UTC, ulimy commented on level2.md
> +하지만 점점 시간이 부족하다. 포기한다.
이거 완전 제 얘기 잖아요 😂

2022-06-02 15:43 UTC, ulimy commented on level2.md
> +우테코를 들어온 이후의 내 학습 계기는 ‘필요’로 뚜렷하게 바뀌었다. 우테코에서는 미션을 하기 전이 아닌 끝난 뒤에 강의가 진행된다. 한정된 지식으로 미션을 해보면서 피부로 그 어려움을 느낀다.
학습계기가 바뀐 것 보다 어려움을 느낀것이 더 과거일텐데 학습계기는 과거형이고 어려움을 느끼는 것은 현재형이라 조금 어색한 것 같아요. 어려움을 느꼈다 라고 하면 어떨까요?

2022-06-02 15:43 UTC, ulimy commented on level2.md
> +딱 필요한 부분만 학습하므로 오로지 그 부분에만 집중하면 된다. 그 사이에 아는 즐거움을 느낄 수 있고 학습의 효율을 높인다.
칙촉만의 학습 효율을 높이는 법이 잘 드러나서 좋네요!

2022-06-04 17:54 UTC, OzRagwort reviewed
안녕하세요 칙촉! 알린이에요

글에서부터 많은 고민을 했다는 것이 느껴지고 마지막 TDD에 비유한 칙촉만의 학습법이 참 공감이 되는 것 같아요. 

칙촉을 보면 잘 웃고 긍정적인 에너지를 받아서 함께하고 싶은 크루인 것 같아요! 칙촉 파이팅!

2022-06-04 17:54 UTC, OzRagwort commented on level2.md
> +딱 필요한 부분만 학습하므로 오로지 그 부분에만 집중하면 된다. 그 사이에 아는 즐거움을 느낄 수 있고 학습의 효율을 높인다.
이번 레벨에서 제가 느낀 것과 비슷한 점인 것 같아서 공감이 되네요.

필요한 부분을 집중해서 공부하는 것을 TDD에 비유하신 점 너무 인상적이에요!

2022-06-04 17:54 UTC, OzRagwort commented on level2.md
> +우테코에서는 페어프로그래밍을 하거나 크루들과 토론할 기회가 많다. 거기서 문제가 생겼다.
`페어프로그래밍`을 혹시 `페어 프로그래밍`이라고 적는게 맞지않을까 생각되는데 어떻게 생각하세요??

글에서 어떤 수정할 점을 찾지 못했지만 코멘트가 없으면 서운하니까 딴지하나 걸어봤습니다.. 😃

2022-06-05 04:57 UTC, hyunrrr commented on level2.md
> +우테코를 들어오기 전 나의 학습 계기는 뚜렷하지 않았다. 예를 들어 자전거 잘 타는 법을 배운다고 가정해보자. 이거 알아두면 나중에 도움 되겠다는 생각으로
```예를 들어```와 ```가정해보자```가 같은 의미를 반복한다고 생각해요!!! 둘 중 하나의 표현만 사용하시는게 어떨까요?

2022-06-05 04:59 UTC, hyunrrr commented on level2.md
> +정리하자면 학습의 계기가 뚜렷하지 않다 보니 이것저것 한 번에 여러 지식을 학습하게 된다. 결과적으로 학습 후에 잘 사용하지 않는 지식은 휘발성이 강하다. 이걸 막기 위해서 시간을 들여서 반복한다.
```결과적으로```가 오히려 문맥의 흐름을 어색하게 만드는거 같아요!!
```결과적으로```를 빼는건 어떨까요?

2022-06-05 05:44 UTC, hyunrrr commented
칙촉 안녕하세요!!!! 글쓰기에서 만나니 너무 반갑네요!!!

몇가지 피드백 남겼습니다!!! 제가 글을 잘 못쓰는 사람이라 피드백이 부정확할 수 있어요!!! 피드백 중에 칙촉이 납득되시는 것만 반영해주세요!!!

글 잘 읽었습니다!! 진짜 너무 공감되는 내용이네요... 필요에 의한 학습을 한다가 인상깊었습니다! 저도 공부를 하며 필요가 없는 것을 공부할때 가장 재미없고 기억에도 안남았던거 같아요!!
tdd를 이용해 현재 학습방법을 표현하신게 너무 멋지네요!!
우테코에서 항상 강조하던게 tdd였는데 tdd스러운 학습방법을 통해 칙촉이 우테코에서 가장 강조되는 개발자가 될 수 있길 응원하겠습니다!!! 화이팅!!!

2022-06-05 07:19 UTC, Juhyung990122 reviewed
안녕하세요 칙촉! 열음입니다:)
이번 글쓰기 미션으로 처음 뵈었는데요!
초면이지만 칙촉이 쓴 글을 읽으며 저와 학습방식이 비슷하다는 생각을 했던 것 같아요ㅎㅎ
자잘한 코멘트를 남겨두었으니 확인부탁드려요!

2022-06-05 07:19 UTC, Juhyung990122 commented on level2.md
> +정리하자면 학습의 계기가 뚜렷하지 않다 보니 이것저것 한 번에 여러 지식을 학습하게 된다. 결과적으로 학습 후에 잘 사용하지 않는 지식은 휘발성이 강하다. 이걸 막기 위해서 시간을 들여서 반복한다.
"결과적으로" 뒷내용이 대조이니 "하지만"으로 바꾸면 자연스러울 것 같아요.

2022-06-05 07:19 UTC, Juhyung990122 commented on level2.md
> +마찬가지로 프로그래밍 학습 또한 새로운 개념을 맞이했을 때 정말 내가 사용할 부분에 대해서만 학습한다. 그래서 내가 실제 사용하지 않을 지식은 제외한다.
오 저와 비슷하시네요! 저도 실제로 사용하지 않을 지식은 과감히 버리니 오히려 필요한것들이 명확해져서 좋더라구요ㅎㅎ

2022-06-06 02:39 UTC, Youngyoon-1 commented on level2.md
> +하지만 점점 시간이 부족하다. 포기한다.
앗 그런가요 ㅎㅎ

2022-06-06 11:19 UTC, Youngyoon-1 commented on level2.md
> +우테코를 들어온 이후의 내 학습 계기는 ‘필요’로 뚜렷하게 바뀌었다. 우테코에서는 미션을 하기 전이 아닌 끝난 뒤에 강의가 진행된다. 한정된 지식으로 미션을 해보면서 피부로 그 어려움을 느낀다.
아리 피드백 감사합니다!!
제 의도는 과거보다는 우테코가 어떤식으로 미션이 진행되는지 를 말하고 싶었는데 혹시 이대로 괜찮을까요?

2022-06-06 11:19 UTC, Youngyoon-1 commented on level2.md
> +딱 필요한 부분만 학습하므로 오로지 그 부분에만 집중하면 된다. 그 사이에 아는 즐거움을 느낄 수 있고 학습의 효율을 높인다.
감사합니다!! 🙇‍♂️

2022-06-06 11:20 UTC, Youngyoon-1 commented on level2.md
> +딱 필요한 부분만 학습하므로 오로지 그 부분에만 집중하면 된다. 그 사이에 아는 즐거움을 느낄 수 있고 학습의 효율을 높인다.
ㅎㅎ 감사합니다~ 알린이 공감을 잘 해주셔서 힘이나네요!

2022-06-06 11:21 UTC, Youngyoon-1 commented on level2.md
> +우테코에서는 페어프로그래밍을 하거나 크루들과 토론할 기회가 많다. 거기서 문제가 생겼다.
네 바로 적용하겠습니다. 피드백 감사합니다!!

2022-06-06 11:21 UTC, Youngyoon-1 commented on level2.md
> +우테코를 들어오기 전 나의 학습 계기는 뚜렷하지 않았다. 예를 들어 자전거 잘 타는 법을 배운다고 가정해보자. 이거 알아두면 나중에 도움 되겠다는 생각으로
오 피드백 감사합니다. 바로 적용했어요!!

2022-06-06 11:22 UTC, Youngyoon-1 commented on level2.md
> +정리하자면 학습의 계기가 뚜렷하지 않다 보니 이것저것 한 번에 여러 지식을 학습하게 된다. 결과적으로 학습 후에 잘 사용하지 않는 지식은 휘발성이 강하다. 이걸 막기 위해서 시간을 들여서 반복한다.
다시 읽어보니 어색하네요ㅎㅎ `결과적으로` 대신 `하지만`으로 대체했습니다!!

2022-06-06 11:43 UTC, Youngyoon-1 commented on level2.md
> +정리하자면 학습의 계기가 뚜렷하지 않다 보니 이것저것 한 번에 여러 지식을 학습하게 된다. 결과적으로 학습 후에 잘 사용하지 않는 지식은 휘발성이 강하다. 이걸 막기 위해서 시간을 들여서 반복한다.
피드백 감사합니다 ㅎㅎ 말씀대로 `하지만`으로 바꾸니 문장이 훨씬 자연스러워졌네요. 감사합니다.ㅎㅎ

2022-06-06 11:44 UTC, Youngyoon-1 commented on level2.md
> +마찬가지로 프로그래밍 학습 또한 새로운 개념을 맞이했을 때 정말 내가 사용할 부분에 대해서만 학습한다. 그래서 내가 실제 사용하지 않을 지식은 제외한다.
오!! 열음도 저와 같은 학습법을 찾으셨다니 👍👍👍

2022-06-06 12:09 UTC, Youngyoon-1 commented on level2.md
> +마찬가지로 프로그래밍 학습 또한 새로운 개념을 맞이했을 때 정말 내가 사용할 부분에 대해서만 학습한다. 그래서 내가 실제 사용하지 않을 지식은 제외한다.
오 열음도 이렇게 느끼셨다니 신기하네요!! ㅎㅎ 남은 기간 같이 화이팅입니다!!

2022-06-06 14:56 UTC, cks3066 reviewed
반가워요 칙촉👋
칙촉의 생각이 잘 드러나있는 글 재미있게 읽었습니다!
욕심내서 이것저것 다 배우려고 하다가 이도저도 아니게 되어버리는 그런 불상사를 막기위해
나에게 필요한 부분만 잘 선정해서 학습한다! 이것이 칙촉의 TDD 학습법이군요!
많이 느끼고 갑니다 ㅎㅎ
남은 우테코 생활 화이팅이에요!!!

2022-06-06 14:56 UTC, cks3066 commented on level2.md
> +하지만 우테코를 시작한 뒤에 문제가 생겼다. 우테코에서는 페어 프로그래밍을 하거나 크루들과 토론할 기회가 많다. 거기서 내 주장에 대한 근거를 제시할 때 아 진짜 이럴까? 스스로 의문이 든다. 그래서 내 주장에 자신이 없다. 앞서 말한 것처럼 프로그래밍하다 보면 명확한 정답이 없는 문제들을 맞닥뜨리게 된다. case a, case b, case c 에 대
페어 혹은 협업에서 토론하고 협의를 할 때, 겉핡기식으로 알고있는 지식들때문에 오히려 혼동이 왔던 기억이 나네요😂

2022-06-06 14:56 UTC, cks3066 commented on level2.md
> +매번 나는 안정적인 기준들을 찾기 위해서 노력하고 우테코는 그걸 흔들고 부순다. 지금은 이렇게 공부하고 있지만 또 언제 바뀔지 모른다. 하지만 걱정 없다. 그 속에서 나는 계속 학습을 이어 나가고 발전할 것이다.
`하지만 걱정 없다.`
자신감과 확고한 의지가 느껴져서 참 좋은데요?👍

2022-06-06 15:12 UTC, woong7 reviewed
안녕하세요, 칙촉!
저도 뜨끔하게 만드는 도입부로 시작하는 흥미로운 글 잘 읽었습니다.
여러 소제목들을 붙여 주셔서 파악하기 쉬운 글이 된 것 같습니다.
굳이 피드백 할 만한 사항을 몇 가지 짜내어 남겨 보았습니다. 
앞으로 칙촉과 많은 대화를 나눠보고 싶어집니다. 잘 읽었습니다!

2022-06-06 15:12 UTC, woong7 commented on level2.md
> +하지만 앞으로 공부해야 할 건 더 많아지고 시간은 더 촉박해진다. 결국 자전거도 잘 타는 게 쉬운 게 아니라고 합리화하고 포기한다.
뼈를 맞은 느낌이 들게 하는 문장이네요..

2022-06-06 15:12 UTC, woong7 commented on level2.md
> +그렇게 하면 새로운 개념에 대한 학습의 필요성을 강하게 느낄 수 있다. 이유가 있는 학습을 하다 보니 깨달음의 재미가 있고 깊이 있는 학습을 할 수 있는 에너지가 생긴다.
`이유가 있는 학습을 하다 보니 깨달음의 재미가 있고, 깊이 있는 학습을 할 수 있는 에너지가 생긴다.`
쉼표 하나 찍어주시면 어떨까요??

2022-06-06 15:12 UTC, woong7 commented on level2.md
> +매번 나는 안정적인 기준들을 찾기 위해서 노력하고 우테코는 그걸 흔들고 부순다. 지금은 이렇게 공부하고 있지만 또 언제 바뀔지 모른다. 하지만 걱정 없다. 그 속에서 나는 계속 학습을 이어 나가고 발전할 것이다.
아직 칙촉과 많은 대화를 나눠보지는 못했지만, 칙촉이라면 상황이 또 바뀌더라도 좋은 학습법을 찾을 수 있을 것이라 생각합니다!

2022-06-07 06:23 UTC, Youngyoon-1 commented on level2.md
> +그렇게 하면 새로운 개념에 대한 학습의 필요성을 강하게 느낄 수 있다. 이유가 있는 학습을 하다 보니 깨달음의 재미가 있고 깊이 있는 학습을 할 수 있는 에너지가 생긴다.
피드백 감사합니다!!

2022-06-07 06:32 UTC, Youngyoon-1 commented on level2.md
> +매번 나는 안정적인 기준들을 찾기 위해서 노력하고 우테코는 그걸 흔들고 부순다. 지금은 이렇게 공부하고 있지만 또 언제 바뀔지 모른다. 하지만 걱정 없다. 그 속에서 나는 계속 학습을 이어 나가고 발전할 것이다.
ㅎㅎ 감사합니다!!

2022-06-07 06:34 UTC, Youngyoon-1 commented on level2.md
> +하지만 우테코를 시작한 뒤에 문제가 생겼다. 우테코에서는 페어 프로그래밍을 하거나 크루들과 토론할 기회가 많다. 거기서 내 주장에 대한 근거를 제시할 때 아 진짜 이럴까? 스스로 의문이 든다. 그래서 내 주장에 자신이 없다. 앞서 말한 것처럼 프로그래밍하다 보면 명확한 정답이 없는 문제들을 맞닥뜨리게 된다. case a, case b, case c 에 대
오 그렇네요! 말씀대로 과거형 어미로 통일시켜줬더니 한결 괜찮아졌네요!! 감사합니다! 판다 👍

2022-06-07 06:38 UTC, Youngyoon-1 commented on level2.md
> +매번 나는 안정적인 기준들을 찾기 위해서 노력하고 우테코는 그걸 흔들고 부순다. 지금은 이렇게 공부하고 있지만 또 언제 바뀔지 모른다. 하지만 걱정 없다. 그 속에서 나는 계속 학습을 이어 나가고 발전할 것이다.
응원 감사합니다!! 판다와 대화 나눠보고 싶어요! 남은 2레벨 같이 화이팅하시죠!!

2022-06-07 06:41 UTC, cks3066 approved these changes
칙촉~!! 바쁜 와중에도 수정하시느라 고생많으시네요😂
저는 바로 Approve 하겠습니다!!
나중에 대화도 같이 나눌 기회라도 있으면 좋겠네요~~!!

2022-06-07 06:51 UTC, hyunrrr approved these changes
칙촉 안녕하세요!!! 미션하시면서 글쓰기 하시느라 정말 고생많이 하셨습니다!!!!
글에서 칙촉의 생각을 알 수 있게 되서 너무 좋았어요!!! 얼마 남지 않은 레벨2 잘 마무리 하시고
남은 우테코기간 동안 칙촉에게 맞는 학습방법을 찾으시길 응원하겠습니다!!! 화이팅!!

2022-06-07 07:30 UTC, OzRagwort approved these changes
앞에서 열심히 코딩중인 칙촉 안녕하세요

칙촉의 글을 읽고 공부를 TDD에 비유하신게 인상 깊어요

사실 글은 이미 잘 쓰셨다고 느꼈는데 수정되고 나니 더 잘 읽히는 것 같아요

좋은 글 잘 읽었습니다.

2022-06-07 10:36 UTC, ulimy approved these changes
안녕하세요 칙촉! 변경사항 확인 했습니다.
팀 미션에 글쓰기까지 정신 없으실텐데 마지막까지 같이 힘내봅시다!

2022-06-07 10:40 UTC, woong7 approved these changes
안녕하세요 칙촉!
피드백 반영해 주셔서 감사합니다:)
다들 미션에 치여 정신없는 와중에도 글쓰기 미션 잘 해주셨어요!
이만 approve 하겠습니다. 방학식까지 같이 힘내요!

2022-06-07 11:43 UTC, Juhyung990122 approved these changes

2022-08-04 02:12 UTC, gracefulBrown approved these changes
👍

2022-08-04 02:12 UTC, merged