[레벨2 글쓰기 미션] 온스타(온승찬) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #189
Opened 2022-05-30 06:39 UTC by cks3066

안녕하세요! 리뷰어분들!!  이번 미션의 유일한 프론트 온스타입니다🤩
사실 미션 1차 PR 기간을 착각하고 있다가 허겁지겁 써버렸어요 ㅠㅠ
그래서 내용이 중구난방 얼렁뚱땅입니다.. 하핫.. 
아무쪼록 잘 부탁드립니다!! 🙏

칙촉 @Youngyoon-1
아리 @ulimy
조시 @hyunrrr
열음 @Juhyung990122
알린 @OzRagwort
판다 @woong7

2022-06-02 15:50 UTC, ulimy requested changes
안녕하세요 온스타~ 아리입니다!
이렇게 인연을 맺게 되네요ㅎㅎ
내용이 깔끔하고 흥미로워 재미나게 읽었습니다!
몇가지 남겨보았는데요! 작은 의견일 뿐이니 꼭 적용하실 필요는 없다는 점 알아주시길 바랍니다ㅎㅎ

2022-06-03 06:47 UTC, Juhyung990122 reviewed
안녕하세요 온스타!
글쓰기로 처음 뵙게 되었네요ㅎㅎ 만나서 반갑습니다.
기존의 전공인 법을 학습하는 방법과 비교하여 표현해주셔서 흥미롭게 읽었어요:)
소소한 코멘트를 몇개 남겨보았는데 한번 읽어봐주세요ㅎㅎ
한번도 뵌적은 없지만 먼 발치에서나마 온스타의 "함께 성장하는 우테코"를 응원할게요:)
파이팅!!

2022-06-03 06:47 UTC, Juhyung990122 commented on level2.md
> +이런 점 덕분에, 법을 공부하던 나는 프로그래밍 공부에 어렵지 않게 적응할 수 있었다. 더욱이, 개발에 필요한 방대한 양의 정보가 인터넷 속에 있고, 언제든 그 정보에 쉽게 접근할 수 있다는 프로그래밍 공부에서의 장점이 이 분야에 더 빠져들 수 있게 해 주었다.
"언제든 그 정보에 쉽게 접근할 수 있다는 장점이 프로그래밍 공부에 더 빠져들 수 있게 해 주었다." 어떠신가요!

2022-06-03 06:47 UTC, Juhyung990122 commented on level2.md
> +법전의 법조항들을 공부하고, 판례를 읽고 또 읽으며 체화시킨 뒤, 분쟁 사항에 대해서 적용할 수 있는 법 조항을 찾고 적용하는 과정이 내가 지금까지 공부했던 법을 공부하는 법이었다.
내가 지금까지 공부했던 `법`을 공부하는 법이었다. 
하이라이트를 주면 가독성이 조금 더 올라갈 것 같아요!

2022-06-04 16:54 UTC, OzRagwort reviewed
안녕하세요 온스타 알린이에요! 

저도 우테코에 오면서 혼자 자라기의 한계를 느끼고 함께 자라기를 실천하기 위해 노력 중인 것 같아요

글이 잘 정리되어있어서 간단한 코멘트하나만 드렸어요!

2022-06-04 16:54 UTC, OzRagwort commented on level2.md
> +앞서 말했듯, 프로그래밍 공부 과정에서 필요한 지식은 인터넷에서 쉽게 얻을 수 있다. 이 점 덕분에 독학으로 프로그래밍을 시작했던 나는, 크게 노력하지 않아도 필요한 정보들을 얻고 공부를 할 수 있었다.
(이 부분은 기존 글도 너무 좋은데 하나라도 코멘트를 드려보고 싶어서 적어봤어요! 기존 글이 더 좋다고 생각하시면 넘기셔도 좋아요!)
이 단락의 주제와 뒤 내용이 크루들과의 협업, 토의를 통한 함께 자라기를 실천하겠다는 내용인 것 같아요
앞부분에서는 대조가 잘되도록 독학을 하면서도 부족함을 느끼지 못했다는 내용이 강조되면 어떨까요?

```suggestion
앞서 말했듯, 프로그래밍 공부 과정에서 필요한 지식은 인터넷에서 쉽게 얻을 수 있다. 이 점 덕분에 나는 크게 노력하지 않아도 필요한 정보들을 얻어 공부를 할 수 있었고 독학으로 프로그래밍을 시작하면서 부족함을 느끼지 못했다.
```

```suggestion
앞서 말했듯, 프로그래밍 공부 과정에서 필요한 지식은 인터넷에서 쉽게 얻을 수 있기 때문에 독학으로 공부하며 혼자 자라기를 하고 있었다.
```
이런 느낌으로요 😃

2022-06-05 07:17 UTC, hyunrrr commented
온스타 안녕하세요!! 처음뵙겠습니다!!! 백엔드의 조시입니다!!!

글 너무 잘쓰셔서 재밌게 막힘없이 읽었습니다!!! 제가 드릴 피드백이 없네요!!

이전에 공부하셨던 법과 현재 공부하는 개발을 비교하며 글 쓰신게 너무 인상적이고 재밌었습니다!!!
법은 잘 몰랐는데 개발과 학습하는 방법에서 공통점이 있네요!! 신기하네요!!
옆의 동료들과 함께 걸어가며 성장할 수 있도록 노력한다는 말이 너무 좋네요. 언젠가 온스타와 함께 협업할 수 있는 기회가 왔으면 좋겠습니다!!!
남은 우테코 생활도 화이팅입니다!!!

2022-06-06 14:35 UTC, woong7 reviewed
안녕하세요, 온스타! 
도입부부터 흥미로운 글 잘 읽었습니다. 
급하게 쓰셨다고 했음에도 불구하고, 딱히 피드백 할 거리를 찾기 어려울 만큼 흡입력이 있었네요. 
한 문장에 여러 개의 쉼표가 들어간 부분이 전반적으로 존재해서, 문장을 분리하면 어떨까 하는 생각도 들었습니다. 그러나 현재 상태로도 충분히 읽기 편해서 이 부분은 지적이 아닌 선택의 영역으로 받아들여 주세요!  
잘 읽었습니다!

2022-06-06 14:35 UTC, woong7 commented on level2.md
> +법전의 법조항들을 공부하고, 판례를 읽고 또 읽으며 체화시킨 뒤, 분쟁 사항에 대해서 적용할 수 있는 법 조항을 찾고 적용하는 과정이 내가 지금까지 공부했던 법을 공부하는 법이었다.
도입부만 읽어도 끝까지 읽어보고 싶게 만드는 흡입력이 있네요!

2022-06-06 14:35 UTC, woong7 commented on level2.md
> +비단, 우테코 뿐만 아니라 많은 개발자 집단에서 대화를 통한 팀원들과의 공동 성장 지향할 것이라고 생각한다. 나는 이 과정에서 많은 효용을 느꼈고, 앞으로도 혼자 걸어가는 것이 아닌 내 옆의 동료들과 함께 걸어가며 함께 성장할 수 있도록 노력할 것이다.
`비단, 우테코 뿐만 아니라 많은 개발자 집단에서 대화를 통한 팀원들과의 공동 성장 지향할 것이라고 생각한다`
쉼표는 제거해도 괜찮을 것 같아요!

2022-06-07 01:24 UTC, cks3066 commented on level2.md
> +앞서 말했듯, 프로그래밍 공부 과정에서 필요한 지식은 인터넷에서 쉽게 얻을 수 있다. 이 점 덕분에 독학으로 프로그래밍을 시작했던 나는, 크게 노력하지 않아도 필요한 정보들을 얻고 공부를 할 수 있었다.
좋은 수정 방향인 것 같아요!

2022-06-07 02:16 UTC, Youngyoon-1 approved these changes
반가워요~ 저희 팀 유일한 프론트 온스타 저는 칙촉이라고 합니다.
우테코 이전과 이후의 공부 방법을 잘 풀어 써주셔서 읽기 편했어요!
이전까지 전 혼자 할 수 있는 공부 방법만을 생각했는데 온스타의 글을 읽고 나서 다시 한번 생각해보게 됐어요.
돌이켜 생각해보니 크루들과의 대화 속에서 얻는 것들이 정말 많았던 것 같아요. 저도 온스타 처럼 혼자 걸어가는 것이 아닌 내 옆의 동료들과 함께 걸어가며 함께 성장할 수 있도록 노력해보겠습니다!!
좋은 글 잘 읽었습니다. 감사합니다.
남은 2레벨도 화이팅!!!!!

2022-06-07 02:34 UTC, OzRagwort approved these changes
안녕하세요 온스타! 

사실 바로 approve 해도 될 것 같은 글이었는데 수정 후 더 좋아진 것 같아요 

좋은 글 잘 읽었습니다 ! 😃

2022-06-07 05:24 UTC, hyunrrr approved these changes
온스타 미션하시고 글쓰기 하시느라 고생하셨습니다!!! 다음에 꼭 같이 공부할 수 있는 기회가 생겼으면 좋겠네요!! 며칠 안남은 레벨2도 화이팅입니다!!!

2022-06-07 10:38 UTC, woong7 approved these changes
안녕하세요, 온스타!
프론트분들도 다들 미션하느라 많이 바빠보이시던데, 좋은 글 써주셔서 잘 읽었습니다. 
이만 approve 할게요!

2022-06-07 11:43 UTC, Juhyung990122 approved these changes

2022-08-04 02:14 UTC, gracefulBrown approved these changes
👍

2022-08-04 02:14 UTC, merged