[레벨2 글쓰기 미션] 아놀드(한수빈) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #191
Opened 2022-05-30 06:48 UTC by sanaandmomo

https://github.com/sanaandmomo/woowa-writing-4/blob/sanaandmomo2/level2.md 
편하게 보기

여러분들 만나서 반가워여~~

2022-05-31 12:17 UTC, jurlring commented on level2.md
> +'다른 크루들은 미션과 공부 두 마리 토끼를 둘 다 잡았던데 나는 왜 그러지 못했을까?'
미션을 잡은 것도 정말 대단한 일이에요! :)
저는 어째 둘 다 못잡은 것 같은.. ㅠ.ㅠ

2022-05-31 12:17 UTC, jurlring commented on level2.md
> +여러분들은 같은 영화나 드라마 혹은 만화를 반복해서 본 적이 있는가?
여러분들이라는 말이 좀 어색한 것 같아요.
~가? 이렇게 높임법을 사용하지 않고 있는데, 주어는 높임을 사용한 단어라서 어색한 것 같아요.

2022-05-31 12:17 UTC, jurlring commented on level2.md
> +난 '진격의 거인'이라는 만화를 즐겨 봤다.
저도 재밌게 봤어요 😄

2022-05-31 12:17 UTC, jurlring commented on level2.md
> +얼마 남지 않은 우테코 생활, 같이 으쌰 으쌰 해자!
아놀드 화이팅 :)

2022-05-31 12:20 UTC, jurlring reviewed
아놀드 안녕하세요! 
글 재밌게 읽었어요.
반복이라는 것은 정말 중요하지만, 포비가 말씀하셨다싶이 목적의식이 있는 반복 연습이 중요한 것 같아요.

우테코 생활 동안 나에게 잘 맞는 학습 방법을 찾는 것 만해도 정말 대단한 거라고 생각해요.
level 2가 거의 끝나가는데 정말 고생하셨어요,

항상 행복하세요! 😄

2022-06-01 13:43 UTC, leo0842 reviewed
안녕하세요 아놀드! 진격의 거인을 반복 숙달했던 아놀드의 경험을 바탕으로 글을 써주셔서 재밌게 읽었습니다!

혹시 제가 말씀드린 부분이 공감이 되신다면 수정해주셔도 좋습니다!!

2022-06-01 13:43 UTC, leo0842 commented on level2.md
> +**진격의 거인 스포 주의**
이 부분은 잘못 들어간 것 같습니다!

2022-06-01 13:43 UTC, leo0842 commented on level2.md
> +그리고 난 '반복'이라는 키워드가 공부의 핵심이라 생각한다.
`그리고` 라는 접속부사는 다소 어색한 것 같습니다!

2022-06-01 23:47 UTC, sanaandmomo commented on level2.md
> +'다른 크루들은 미션과 공부 두 마리 토끼를 둘 다 잡았던데 나는 왜 그러지 못했을까?'
사실 저도요... 같이 힘냅시다!!

2022-06-01 23:48 UTC, sanaandmomo commented on level2.md
> +여러분들은 같은 영화나 드라마 혹은 만화를 반복해서 본 적이 있는가?
그러네요! 당신들은 이라고 바꾸겠습니다!

2022-06-01 23:48 UTC, sanaandmomo commented on level2.md
> +난 '진격의 거인'이라는 만화를 즐겨 봤다.
명작이죠 ㄷㄷ

2022-06-01 23:48 UTC, sanaandmomo commented on level2.md
> +여러분들은 같은 영화나 드라마 혹은 만화를 반복해서 본 적이 있는가?
그러네요! 당신들은 이라고 바꾸겠습니다!

2022-06-01 23:49 UTC, sanaandmomo commented on level2.md
> +얼마 남지 않은 우테코 생활, 같이 으쌰 으쌰 해자!
주디 화이팅!!

2022-06-01 23:49 UTC, sanaandmomo commented on level2.md
> +**진격의 거인 스포 주의**
어떤게 잘못 들어간지 정확하게 모르겠습니다!

2022-06-01 23:50 UTC, sanaandmomo commented on level2.md
> +그리고 난 '반복'이라는 키워드가 공부의 핵심이라 생각한다.
그럼 어떤게 좋을까요?

2022-06-03 11:39 UTC, jayjaehunchoi approved these changes
아놀드 멋진 마음을 가진 분이시네요!
앞으로도 체화하는 공부 화이팅 하십쇼!!!

2022-06-03 11:39 UTC, jayjaehunchoi commented on level2.md
> +짧은 주기를 기반으로 반복적으로 학습해서 몸에 체화시키는 강력한 공부법이다.
저도 한 때 이런 공부법을 에용헸었죠 ㅎㅎ

2022-06-03 11:39 UTC, jayjaehunchoi commented on level2.md
> +"가장 빠르게 가는 법은 올바르게 가는 법이다" - '유명한 사람'
지름길로 가지 않으려는 모습 멋지십니다.

2022-06-05 10:38 UTC, DWL21 requested changes
안녕하세요 레오입니다. 글 잘 읽었습니다. 내적 독백을 사용하여 자신의 심정을 들어낸 부분이 인상깊네요. 다만 문장에 쉼표와 접속사가 많아서 한 문장에 한 정보만 담고 자연스러운 흐름으로 이뤄지게 글을 바꿔보면 좋을 것 같아요!

2022-06-05 10:38 UTC, DWL21 commented on level2.md
> +숨 쉴 때마다 '이것은 공기, 식물이 광합성을 통해 내뿜는 물질' 이라고 생각하지 않는 것처럼, 정말 당연한 존재다.
계획을 세우고 지키는건 어려운 일이죠.

2022-06-05 10:38 UTC, DWL21 commented on level2.md
> +하지만 반복 학습 덕분에 처음이 이해가 안 갔던 내용들을 어렴풋이 이해할 수 있게 됐다.
접속사를 안 쓰고 문장을 자연스럽게 이어볼 수 있을까요??

2022-06-05 10:38 UTC, DWL21 commented on level2.md
> +"가장 빠르게 가는 법은 올바르게 가는 법이다" - '유명한 사람'
크 좋은 말 이네요.

2022-06-05 15:21 UTC, Gyuchool reviewed
아놀드.. 역시...재밌네여
글을 너무 재밌게 읽었습니다! 아놀드는 최고네여😎

2022-06-05 15:21 UTC, Gyuchool commented on level2.md
> +난 '진격의 거인'이라는 만화를 즐겨 봤다.
저도 다 봤어여~😄

2022-06-05 15:21 UTC, Gyuchool commented on level2.md
> +"뭐 네 번이나 읽었다고? 어우 지루해! 할 짓이 그렇게 없었어?"
아.. 보이는 라디오.. 놀드형 목소리가 들리네여..

2022-06-06 04:32 UTC, sanaandmomo commented on level2.md
> +짧은 주기를 기반으로 반복적으로 학습해서 몸에 체화시키는 강력한 공부법이다.
크...

2022-06-06 04:33 UTC, sanaandmomo commented on level2.md
> +"가장 빠르게 가는 법은 올바르게 가는 법이다" - '유명한 사람'
크...

2022-06-06 04:34 UTC, sanaandmomo commented on level2.md
> +숨 쉴 때마다 '이것은 공기, 식물이 광합성을 통해 내뿜는 물질' 이라고 생각하지 않는 것처럼, 정말 당연한 존재다.
음..? 어떤 부분이 계획처럼 느껴지셨나요?

2022-06-06 04:35 UTC, sanaandmomo commented on level2.md
> +하지만 반복 학습 덕분에 처음이 이해가 안 갔던 내용들을 어렴풋이 이해할 수 있게 됐다.
히지만을 이제는으로 고치면 어떨까요?

2022-06-06 04:35 UTC, sanaandmomo commented on level2.md
> +"뭐 네 번이나 읽었다고? 어우 지루해! 할 짓이 그렇게 없었어?"
기론도 재밌죠~~~

2022-06-06 23:11 UTC, al-bur approved these changes
안녕하세요 아놀드 앨버입니다!!

놀드의 비기 잘 보았어요ㅎㅎ저도 이번 방학때 놀드의 비기를 사용해서 공부해보려고합니다~
흥미롭게 글 작성해주셔서 재밌게 읽었어요!!!

2022-06-07 07:18 UTC, byhhh2 reviewed
와 아놀드의 생각이 살짝 궁금해서 들렸는데
진짜 글이 너무 웃기네요. 이제껏 본 글 중에 젤 웃깁니다. ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
크~~  역시 인생은 아놀드처럼 ~ -

2022-06-07 07:18 UTC, byhhh2 commented on level2.md
> +난 이 공부법으로 무려 '우테코'에 합격할 수 있었다!
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 진짜 너무 웃기잖아요 ㅠ

2022-06-07 07:18 UTC, byhhh2 commented on level2.md
> +이러한 여러분들께 '마지막 비기인 **14714**공부법'을 전수하겠다!
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ `전수하겠다!`

2022-06-07 07:18 UTC, byhhh2 commented on level2.md
> +코딩을 할 때마다 숨 쉬듯이 자바스크립트의 개념을 적용한다.
캬..

2022-06-07 07:18 UTC, byhhh2 commented on level2.md
> +"가장 빠르게 가는 법은 올바르게 가는 법이다" - '유명한 사람'
`유명한 사람`ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-06-07 12:21 UTC, Gyuchool approved these changes

2022-06-07 13:48 UTC, DWL21 commented on level2.md
> +숨 쉴 때마다 '이것은 공기, 식물이 광합성을 통해 내뿜는 물질' 이라고 생각하지 않는 것처럼, 정말 당연한 존재다.
반복 학습이라 해서 계획을 세우고 실천해나가는 걸로 잘못 이해했네요 ㅎㅎ. 반복 -> 꾸준함 -> 계획?

2022-06-07 14:09 UTC, leo0842 approved these changes

2022-06-08 12:46 UTC, jurlring approved these changes

2022-08-04 02:14 UTC, gracefulBrown approved these changes
👍

2022-08-04 02:14 UTC, merged