[레벨3 글쓰기 미션] 하리(이아현) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #265
Opened 2022-08-08 04:03 UTC by LAH1203

안녕하세요 글쓰기 제출합니다~!

리차드 @hj-rich
이프 @sinb57
봄 @jangbomi
연로그 @yeon-06
썬 @syoun602

잘 부탁드립니다 🙇‍♀️

2022-08-08 19:02 UTC, HJ-Rich requested changes
안녕하세요 하리, 백엔드 크루 리차드라고 합니다.
글쓰기 미션으로 만나서 반가워요~ :)

글에서 하리만의 매력있는 바이브가 전달되는 것 같아요~
너무 좋네요! ㅎㅎ

행복감이 잘 전달되는데,
만약 에피소드가 하나 정도 소개될 수 있다면
행복감이 더 생생하게 전해질 것 같다는 생각이에요! ㅎ

하리가 퇴고해가며 더 멋진 글로 만들어주실 것 같아서
Request Changes 하겠습니다.

마지막 스프린트를 남겨둔 레벨 3,
그리고 하리의 우테코 섬에서의 남은 여정까지
응원합니다~~ 하리 화이팅!!

2022-08-08 19:02 UTC, HJ-Rich commented on level3.md
> +
이러한 애정이 생기게 된 에피소드 하나를 들려주신다면 더 생동감이 전달될 것 같아요~
들려주실 수 있을까요?! 😄

2022-08-14 09:12 UTC, syoun602 approved these changes
안녕하세요 하리! 글쓰기 미션에서 처음 뵙네요 저는 백엔드 크루 썬이라고 합니다. ☀️
글 너무 잘 읽었습니다! 딱히 고칠 점이 보이진 않아서 감상만 남기고 가네요!
보면서 하리의 팀문화도 방향성도 너무 좋아서 공감만하고 갑니다!  (앗! 물론 저희팀도 하리네의 팀문화만큼 멋집니다 💪)
저는 approve하겠습니다 :)

2022-08-14 09:12 UTC, syoun602 commented on level3.md
> +그런데 정말 소소한 것(스타일링이나 여러 가지 고민에 대한 작은 해결책)에도 팀원들은 '대단해', '멋있어', '최고야' 칭찬을 해주더라고요.
최고로 멋있는 팀원이네요 👍

2022-08-14 09:12 UTC, syoun602 commented on level3.md
> +그게 지금 저의 온전한 목표입니다 🎯
멋지네요 💯 저도 하리의 성장에 초점을 맞춘 방향성에 동감하고 갑니다!!!

2022-08-14 15:08 UTC, yeon-06 approved these changes
안녕하세요 하리~
글을 읽기 좋게 + 리뷰하기 좋게 적절히 나누어주셔서 보는게 너무 편했어요 ㅎㅎㅎ
중간중간 넣어주신 이모티콘도 너무 귀엽네요😆
글 잘 읽었습니다 남은 기간 프로젝트도 파이팅하세요!!!

2022-08-14 15:08 UTC, yeon-06 commented on level3.md
> +그런데 정말 소소한 것(스타일링이나 여러 가지 고민에 대한 작은 해결책)에도 팀원들은 '대단해', '멋있어', '최고야' 칭찬을 해주더라고요.
괄호 보다는 `그런데 스타일링이나 여러 가지 고민에 대한 작은 해결책 같은 소소한 것에도 팀원들은 ~ `이런 식으로 풀어보는건 어떨까요? 
아예 생략하는 방법도 있고요!
괄호가 있으면 저는 문장을 읽다가 앞의 단어가 뭐였는지 다시 보고 그 다음으로 넘어가는 식으로 읽게 되더라고요~
너무 길게 느껴지시면 문장을 나누는 것도 좋은 방법일 것 같아요😄

2022-08-14 15:08 UTC, yeon-06 commented on level3.md
> +모두 모여라 프로젝트는 처음에는 모두가 목표하는 바가 달랐지만 이를 깨닫고 공통의 목표를 설정할 수 있었어요.
공통의 목표는 소통과 관련된 목표일까요?
궁금하네요!!😄

2022-08-14 15:08 UTC, yeon-06 commented on level3.md
> +기술뿐만 아니라 팀의 운영에서도요!
팀의 운영보다는 팀워크라거나... 좀 더 친숙한 단어를 쓰는건 어떨까요?!🙂
팀의 운영이라고 하니 사무적인 느낌이 있어 좀 딱딱하게 느껴지는 것 같아요!

2022-08-15 05:01 UTC, sinb57 commented on level3.md
> +그런데 정말 소소한 것(스타일링이나 여러 가지 고민에 대한 작은 해결책)에도 팀원들은 '대단해', '멋있어', '최고야' 칭찬을 해주더라고요.
저도 공감합니다!

2022-08-15 05:19 UTC, sinb57 approved these changes
모두모여라의 마스코트 하리~!!~!~!!!!

글 잘 읽었어요. 매일매일 옆에서 지켜봐온 하리에게서 보지 못했던
진지한 속마음을 볼 수 있어서 감동이에요. 하리의 글 한줄한줄이 너무나도 공감돼요!!

비록 레벨3는 한 주 남았지만 마지막 남은 한 주도 보람차게 화이팅해봐요!!
모두모여라 화이팅~!!!!

2022-08-15 05:19 UTC, sinb57 commented on level3.md
> +원래 팀 프로젝트를 시작하기 전 제 목표는 `무사히 프로젝트 잘 끝내기`였어요.
```suggestion
원래 팀 프로젝트를 시작하기 전, 제 목표는 `무사히 프로젝트 잘 끝내기`였어요.
```
쉼표 하나 어떤가요??ㅎ

2022-08-15 05:19 UTC, sinb57 commented on level3.md
> +### 목표 이야기
```suggestion
## 목표 이야기
```
글의 흐름을 구분짓기 위해 `옛날 이야기` `지금 이야기` `목표 이야기`를 구분지은 것 같아요!!
그렇다면 `목표 이야기`에도 동일한 마크다운을 적용하는 것은 어떨까요??

2022-08-15 05:19 UTC, sinb57 commented on level3.md
> +그래서 저는 누가 뭐래도 우리 팀이 정말 좋아요 🤗
저도 우리팀 엄청 좋습니다!! 😆 모두모여라 최고!!

2022-08-15 05:19 UTC, sinb57 commented on level3.md
> +레벨 3가 시작하고 6주가 지난 지금, 저에겐 다른 목표가 생겼어요.
```suggestion
레벨 3를 시작하고 6주가 지난 지금, 저에겐 다른 목표가 생겼어요.
```
표현이 어색해서 고쳐봤어요!!

2022-08-15 10:20 UTC, HJ-Rich approved these changes
피드백 반영하신 내용 확인했습니다
✔ 어푸어푸~

2022-08-15 11:33 UTC, syoun602 approved these changes

2022-08-15 11:34 UTC, JangBomi approved these changes
안녕하세요 하리! 글쓰기 미션으로 처음 뵙네요. 너무 반가워요!

하리를 잘 모르지만, 글을 읽는데 하리 정말 멋있는 분이신 것 같다는 생각이 계속 들었어요.
글이 `옛날 이야기 -> 지금 이야기` -> 목표이야기 로 전개되는 방식도 너무 좋고, 리뷰하기 편하게 글이 구분되어있어서 좋았어요.
너무 좋은 글이라, 리뷰보다는 감상만 남겼네요. 하리가 모모팀을 정말 좋아하고, 모모팀과 함께인게 너무 즐거워하는게 글에서 느껴졌어요!

하리 응원하겠습니다 화이팅 👍

2022-08-15 11:34 UTC, JangBomi commented on level3.md
> +> 나는 멋있는 사람이 될 거야! 모두가 나를 부러워할 만큼!
하리 너무 멋있어요..!

2022-08-15 11:34 UTC, JangBomi commented on level3.md
> +> 좋은 프로젝트에는 소통이 필요하다.
맞아요! 저도 너무 공감하는 말입니다!!

2022-10-04 07:44 UTC, gracefulBrown approved these changes
👍

2022-10-04 07:45 UTC, merged