[레벨 3 글쓰기 미션] 빅터(이우승) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #291
Opened 2022-08-08 10:40 UTC by woose28

@juhyung990122 @inkyojeong @ronci @bcc0830 @summerlunaa
안녕하세요! 이번 글쓰기 미션을 함께하게 된 빅터라고 합니다!!

[편하게 보기](https://github.com/woose28/woowa-writing-4/blob/level3/level3.md)

피드백은 언제나 환영입니다ㅎㅎ  읽어주셔서 감사합니다 :-)

2022-08-14 13:55 UTC, ronci reviewed
안녕하세요 빅터! 같은 글쓰기 팀 우연입니다
스모디팀의 활발한 토론 문화로 저도 더 열심히 의견을 낼 수 있어서 팀 문화가 중요하다는 것을 새삼 느끼고 있어요!

소소한 코멘트 남겼는데 한 번 확인 부탁드립니다!

2022-08-14 13:55 UTC, ronci commented on level3.md
> +'혹시 YES맨 아니었나요?', '미션을 하면서 주도적으로 한 것이 있나요?' 면담 시간에 코치님이 해주신 질문이다. 성향상 먼저 나서는 것을 선호하지 않는다. 그리고 다른 사람이 의견을 말하면 '아 그럴 수 있게구나'라는 생각으로 수용적인 태도를 취하는 경향이 있다. 매 순간 위와 같은 태도를 취한건 아니다. 하지만 누군가를 이끄는 것이 아닌 끌려가는
`있게구나`를 `있겠구나`로 맞춤법 고치면 좋을 것 같아요!

2022-08-14 13:55 UTC, ronci commented on level3.md
> +지니치게 수동적이고 수용적인 태도를 지양해야겠다고 생각했다. 수동적인 사람이 갑자기 리더가 되는 것은 맞지 않은 옷을 입는 것처럼 불편한 일이다. 그리고 그 불편함은 팀에게도 전달되어 오히려 도움이 되지 않을 것이다. 하지만 리더가 되지 않아도 앞서 말한 부족한 점을 충분히 개선할 수 있다. 의견을 개진하고, 주장을 피력하는 일을 적극적으로 하는 것만으로
`지니치게`를 `지나치게`로 고치면 좋을 것 같아요!

2022-08-14 13:55 UTC, ronci commented on level3.md
> +프론트 팀원들과 협업할 때도 토론이 활발하다. 팀원들 모두가 YES맨이 아니다. 각자의 의견을 적극적으로 이야기한다. 그리고 토론의 분위기가 편안하게 형성돼 있다. 적극적인 팀원에게 자극받고 편한 분위기 덕에 나 또한 활발히 의견을 제시한다.
다들 의견을 적극적으로 이야기해서 더 편하게 의견을 제시할 수 있어서 좋아요!

2022-08-14 13:55 UTC, ronci commented on level3.md
> +앞으로 더 많은 팀에서 더 많은 사람들과 협업을 할 것이다. 누구와 함께하든 YES맨이 되지 않도록 의식적으로 연습할 것이다. 그리고 지금의 팀원들이 내게 긍정적인 영향을 끼쳤듯이, 나 또한 다른 팀원에게 긍정적인 영향을 주는 사람이 되고 싶다.
제일 첫 문장을 다음과 같이 바꿔보는 건 어떨까요??
 `앞으로 더 많은 팀에서 더 많은 사람과 협업할 것이다.`

2022-08-14 15:12 UTC, summerlunaa reviewed
빅터 안녕하세요 파랑입니다~
YES맨에서 벗어나는 것에 대해 많이 고민한 흔적이 느껴졌어요 ㅎㅎ
저도 비슷한 피드백을 들은 적이 있어서 공감하며 읽었네요!
저는 YES 할 때에도 그냥 좋다고 하지 말고 좋은 이유를 말해보는 걸 개선 방향으로 잡았었답니다!
저번 장바구니 미션 때를 생각해보면 빅터는 스모디에서 좋은 팀원이었을 것 같아요. 남은 일주일도 응원합니다~

2022-08-14 15:12 UTC, summerlunaa commented on level3.md
> +'혹시 YES맨 아니었나요?', '미션을 하면서 주도적으로 한 것이 있나요?' 면담 시간에 코치님이 해주신 질문이다. 성향상 먼저 나서는 것을 선호하지 않는다. 그리고 다른 사람이 의견을 말하면 '아 그럴 수 있게구나'라는 생각으로 수용적인 태도를 취하는 경향이 있다. 매 순간 위와 같은 태도를 취한건 아니다. 하지만 누군가를 이끄는 것이 아닌 끌려가는
저도 안 좋은데 좋다고 하는 거 아니냐는 말을 몇 번 들었어서 ㅋㅋㅋ ㅠㅠ 공감되네요

2022-08-14 15:12 UTC, summerlunaa commented on level3.md
> +프론트 팀원들과 협업할 때도 토론이 활발하다. 팀원들 모두가 YES맨이 아니다. 각자의 의견을 적극적으로 이야기한다. 그리고 토론의 분위기가 편안하게 형성돼 있다. 적극적인 팀원에게 자극받고 편한 분위기 덕에 나 또한 활발히 의견을 제시한다.
의견을 쉽게 개진하기 위해서는 편안한 팀의 분위기가 중요한 것 같아요! 좋네요

2022-08-14 15:12 UTC, summerlunaa commented on level3.md
> +앞으로 더 많은 팀에서 더 많은 사람들과 협업을 할 것이다. 누구와 함께하든 YES맨이 되지 않도록 의식적으로 연습할 것이다. 그리고 지금의 팀원들이 내게 긍정적인 영향을 끼쳤듯이, 나 또한 다른 팀원에게 긍정적인 영향을 주는 사람이 되고 싶다.
긍정적인 영항을 끼치는 빅터를 응원합니다🎊

2022-08-15 11:12 UTC, InKyoJeong approved these changes
빅터안녕하세요 코이입니다ㅎㅎ
글 잘읽었습니다! 팀 프로젝트에 어떤 자세로 임했고 어떻게 노력했는지가 잘 느껴지는 글이였어요~
저도 긍정적인 영향을 주는 사람이 되고싶네요. 남은 기간도 화이팅합시당👍

2022-08-15 11:12 UTC, InKyoJeong commented on level3.md
> +당연한 이야기지만 적극적으로 의견을 피력하다 보면 그냥 수용할 때보다 더 많이 생각하고 말하게 된다. 의식적으로 수용적인 태도를 거부하고 나의 의견을 제시하는 연습을 하고 있다. 연습 덕분인지 이전보다 내 생각을 전달하는 것이 수월하다고 느껴진다. 그리고 말하기에 있어 부담이 줄어들었다.
수용적 태도보다는 의견을 제시하려고 연습하는 모습 좋네요 👍  👍

2022-08-15 11:12 UTC, InKyoJeong commented on level3.md
> +위에서 언급했듯이 스모디팀은 토론이 장려되고 편안한 분위기가 조성돼 있다. 팀원들과 함께 만든 좋은 분위기 속에서 단점이라 생각되는 성향을 개선하고 있다. 이를 통해 긍정적인 팀 분위기와 문화의 중요성을 느꼈다. 그리고 좋은 팀 문화가 팀원을 성장시킬 수 있다는 것을 느꼈다.
`팀문화도 팀원을 성장시킬수있다는것` 저도 느낀 부분이라 공감가네요!!

2022-08-15 12:14 UTC, bcc0830 requested changes
안녕하세요 빅터 알파입니다
글 잘읽었습니다
레벨 3도 같이 힘내서 마무리해봅시다 파이팅

2022-08-15 12:14 UTC, bcc0830 commented on level3.md
> +'혹시 YES맨 아니었나요?', '미션을 하면서 주도적으로 한 것이 있나요?' 면담 시간에 코치님이 해주신 질문이다. 성향상 먼저 나서는 것을 선호하지 않는다. 그리고 다른 사람이 의견을 말하면 '아 그럴 수 있게구나'라는 생각으로 수용적인 태도를 취하는 경향이 있다. 매 순간 위와 같은 태도를 취한건 아니다. 하지만 누군가를 이끄는 것이 아닌 끌려가는
회의 때 조용히 있다가 강력한 한방을 남기는 소강남 빅터씨..

2022-08-15 12:14 UTC, bcc0830 commented on level3.md
> +프론트 팀원들과 협업할 때도 토론이 활발하다. 팀원들 모두가 YES맨이 아니다. 각자의 의견을 적극적으로 이야기한다. 그리고 토론의 분위기가 편안하게 형성돼 있다. 적극적인 팀원에게 자극받고 편한 분위기 덕에 나 또한 활발히 의견을 제시한다.
뿌듯하네요 ^^

2022-08-15 12:38 UTC, woose28 commented on level3.md
> +지니치게 수동적이고 수용적인 태도를 지양해야겠다고 생각했다. 수동적인 사람이 갑자기 리더가 되는 것은 맞지 않은 옷을 입는 것처럼 불편한 일이다. 그리고 그 불편함은 팀에게도 전달되어 오히려 도움이 되지 않을 것이다. 하지만 리더가 되지 않아도 앞서 말한 부족한 점을 충분히 개선할 수 있다. 의견을 개진하고, 주장을 피력하는 일을 적극적으로 하는 것만으로
아이구 맞춤법 검사기만 믿고 오타가 있는지 확인을 안 했네요..! 꼼꼼하게 확인해 주셔서 감사합니다!!

2022-08-15 12:40 UTC, woose28 commented on level3.md
> +앞으로 더 많은 팀에서 더 많은 사람들과 협업을 할 것이다. 누구와 함께하든 YES맨이 되지 않도록 의식적으로 연습할 것이다. 그리고 지금의 팀원들이 내게 긍정적인 영향을 끼쳤듯이, 나 또한 다른 팀원에게 긍정적인 영향을 주는 사람이 되고 싶다.
`사람들`이라는 말이 어색하게 읽혔나 보네요. 제안해 주신 대로 수정하겠습니다!

2022-08-15 12:42 UTC, woose28 commented on level3.md
> +앞으로 더 많은 팀에서 더 많은 사람들과 협업을 할 것이다. 누구와 함께하든 YES맨이 되지 않도록 의식적으로 연습할 것이다. 그리고 지금의 팀원들이 내게 긍정적인 영향을 끼쳤듯이, 나 또한 다른 팀원에게 긍정적인 영향을 주는 사람이 되고 싶다.
훨씬 문장이 자연스러워졌네요! 제안해 주신 대로 수정하겠습니다~

2022-08-15 12:45 UTC, woose28 commented on level3.md
> +앞으로 더 많은 팀에서 더 많은 사람들과 협업을 할 것이다. 누구와 함께하든 YES맨이 되지 않도록 의식적으로 연습할 것이다. 그리고 지금의 팀원들이 내게 긍정적인 영향을 끼쳤듯이, 나 또한 다른 팀원에게 긍정적인 영향을 주는 사람이 되고 싶다.
감사합니다 파랑!!

2022-08-15 12:45 UTC, woose28 commented on level3.md
> +위에서 언급했듯이 스모디팀은 토론이 장려되고 편안한 분위기가 조성돼 있다. 팀원들과 함께 만든 좋은 분위기 속에서 단점이라 생각되는 성향을 개선하고 있다. 이를 통해 긍정적인 팀 분위기와 문화의 중요성을 느꼈다. 그리고 좋은 팀 문화가 팀원을 성장시킬 수 있다는 것을 느꼈다.
오ㅎㅎ 코이도 느끼셨군요!

2022-08-15 12:46 UTC, woose28 commented on level3.md
> +프론트 팀원들과 협업할 때도 토론이 활발하다. 팀원들 모두가 YES맨이 아니다. 각자의 의견을 적극적으로 이야기한다. 그리고 토론의 분위기가 편안하게 형성돼 있다. 적극적인 팀원에게 자극받고 편한 분위기 덕에 나 또한 활발히 의견을 제시한다.
^_^

2022-08-15 13:38 UTC, summerlunaa approved these changes

2022-08-15 14:06 UTC, Juhyung990122 approved these changes
안녕하세요 빅터! 
바쁘신 와중에 글쓰기 미션 하시느라 고생많으셨습니다.
빅터와 성향이 비슷한 것 같아 저도 함께 배워갈 수 있는 글이였네요.
따로 코멘트 드릴 게 없어서 approve 하겠습니다! 파이팅!!

2022-08-15 14:06 UTC, Juhyung990122 commented on level3.md
> +'혹시 YES맨 아니었나요?', '미션을 하면서 주도적으로 한 것이 있나요?' 면담 시간에 코치님이 해주신 질문이다. 성향상 먼저 나서는 것을 선호하지 않는다. 그리고 다른 사람이 의견을 말하면 '아 그럴 수 있겠구나'라는 생각으로 수용적인 태도를 취하는 경향이 있다. 매 순간 위와 같은 태도를 취한건 아니다. 하지만 누군가를 이끄는 것이 아닌 끌려가는
오 저랑 조금 비슷하시네요!! 저도 그럴수있다는 생각을 자주하곤 해요ㅎㅎ

2022-08-15 14:06 UTC, Juhyung990122 commented on level3.md
> +프론트 팀원들과 협업할 때도 토론이 활발하다. 팀원들 모두가 YES맨이 아니다. 각자의 의견을 적극적으로 이야기한다. 그리고 토론의 분위기가 편안하게 형성돼 있다. 적극적인 팀원에게 자극받고 편한 분위기 덕에 나 또한 활발히 의견을 제시한다.
스모디 팀의 비결은 이거였군요👀

2022-08-15 14:45 UTC, ronci approved these changes
수정하시느라 수고하셨어요!
Approve하겠습니다!

2022-08-15 14:53 UTC, bcc0830 approved these changes

2022-10-04 07:43 UTC, gracefulBrown approved these changes
👍

2022-10-04 07:43 UTC, merged