[레벨3 글쓰기 미션] 봄(장보미) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #302
Opened 2022-08-08 12:35 UTC by JangBomi

@sinb57 이프
@yeon-06 연로그
@syoun602 썬
@LAH1203 하리
@HJ-Rich 리차드

안녕하세요 글쓰기 미션으로 만나게 돼서 반갑습니다!

잘 부탁드려요 :)

[편하게 보기](https://github.com/JangBomi/woowa-writing-4/blob/jangbomi/level3.md)

2022-08-08 17:20 UTC, HJ-Rich approved these changes
봄 안녕하세요,

봄의 색깔이 느껴지는 글 잘 읽었습니다!
팀 프로젝트 같이 진행하며 팀을 위해 희생하고 노력해주는 모습
자주 봤어요. 의식적인 노력이었다니 멋집니다.

문장별로 리뷰를 남기기 좋게 개행을 추가하면 어떨까요?
문장별로 개행을 한 번만 하면 Markdown 파일을 보는 입장에선 변화가 없으면서도
리뷰를 주고받기엔 더 수월할 것 같아요.

첫 리뷰 요청에 Approve 하는 게 조심스럽기도 하지만
그렇다고 억까를 하는 건 더 아니니까.. Approve 하겠습니다 ㅎ
제가 보기엔 이미 군더더기 없이 깔끔하네요!
Approve~

고생하셨습니다.
남은 기간 잘부탁드립니다!

2022-08-08 17:20 UTC, HJ-Rich commented on level3.md
> +장바구니 협업 미션에서 내가 가장 크게 얻은 것이 공동의 목표를 세운 것일 정도로 너무나 만족스러웠다. 그래서 레벨3 팀 프로젝트에서도 팀원들 개인의 목표를 듣고, 무조건 팀의 목표를 세워야겠다고 생각했다.
저는 장바구니 때 팀 공동의 목표를 세울 생각은 못해봤던 것 같은데.. 
봄은 그걸 해냈을 뿐만 아니라 결과까지도 만족스러우셨군요
정말 좋은 경험이었을 것 같아요!

2022-08-08 17:20 UTC, HJ-Rich commented on level3.md
> +쉽게 생각했던 팀의 목표 찾기는 사실 굉장히 어려운 일이었다. 우선, 팀원 개인의 목표가 달랐다. 다른 사람 6명이 모이니, 다른 목표 6개가 생겼다. 또, 단어에 대한 정의도 달랐다. 레벨3의 우테코 목표가 `찐~~~~한 협업 경험`이었다. 여기서 나온 `협업`이라는 단어의 정의도 달랐다. 협업하는 방법에 대한 생각이 달랐다.
이제는 시간이 흘러 서로에 대해 더 이해하고 더 맞추기 쉬워진 것 같지만
처음엔 저도 참 신기하기도 하고 당황스럽기도 했어요.
이렇게 다 의견이 다르다니 하고요 ㅋㅋ 
지금 생각하면 재밌기도 하고.. 이처럼 서로 의견이 달랐던 상황도 큰 경험이 될 것 같네요

2022-08-08 17:20 UTC, HJ-Rich commented on level3.md
> +아주 작은 노력이라 팀원들에게 티가 나지 않았을 것 같다. 하지만, 내가 나의 고치고 싶은 점을 알고, 고치려 노력하고 있다는 것, 이 프로젝트로 내가 변화한 모습인 것 같다.
봄이 팀을 위해 노력해준 모습들 저는 자주 느꼈어요.
다들 힘든 상황이었을텐데 그래도 상대를 생각하며 봄이 먼저 한 번 더 희생하는 모습들을 저는 봤거든요.
의견을 더 적극적으로 내려고 노력하는 모습도 느꼈었구요.
미안하고 고마워요.

쉼표가 세 번 들어간 문장이 있는데 물론 의도하신 거겠지만..
혹시 퇴고를 통해 봄이 더 나은 문장으로 만들 수 있지 않을까 하는 기대가 있습니다!

2022-08-14 09:36 UTC, syoun602 requested changes
안녕하세요 봄🌱 썬입니다 ☀️
글 잘읽었어요 :) 레벨 1때 첫 페어때 같이 헤매던게 엊그제 같은데
폭풍 성장한 봄 덕에 저도 덩달아 기분이 좋네요 😊 
항상 밝은 모습이 참 보기 좋은 것 같아요!! 항상 기분이 좋을 수는 없는데,
재미없는 드립에 한결같이 웃어주셔서 감사합니다 🥺 간단한 리뷰 남겼어요!!! 편하게 반영해주세요 ~!

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +### 어려운 팀의 목표 찾기, 하지만 없으면 어때~
```suggestion
### 어려운 팀 목표 찾기, 하지만 없으면 어때~
```
는 어떨까요?!

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +레벨2 장바구니 협업 미션 당시에 팀 공동의 목표를 세웠었다. 그리고 ‘공동의 목표 세우기’는 꽤 잘 동작했다. 회의가 산으로 가거나, 어떤 의사결정을 할 때, ‘우리가 하는 말이 목표에 부합하는가?’ 에 대해 고민하고 올바른 길로 나아갔다. 정답이 없는 사안에 대해서도, 공동의 목표를 기준으로 길을 찾아갔다.
목표 세우기에 `동작했다` 보다는 다른 단어가 더 어울릴 것 같아요!!! 봄은 어떻게 생각하시나요?

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +모든 다름 속에 장바구니 미션 때처럼 딱 정해진 우리 팀의 목표는 세우지 못했다. 하지만 정하지 못한 팀 목표 속에서 우리는 서로의 다름을 인정하고 한 방향을 향해 나아가려고 했다. 지금 돌아보면, 무조건 팀의 목표를 세워야겠다는 생각은 과한 자신감이었던 것 같다. 이번 팀 프로젝트를 통해, 모두의 생각이 다르더라도 시간이 지나며 충분히 맞춰갈 수 있다는
이건 개인적인 의견일 수도 있는데, `같은 방향으로 나아가고자 했다.`가 좀 더 자연스러운 것 같아요 😊

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +팀 프로젝트뿐만 아니라, 어떤 모임에서 내가 가장 많이 하는 말이 `좋아~`이다. A의 의견을 들으면 A의 의견이 좋아 보이고, B의 의견을 들으면 B의 의견이 좋아 보인다. 이번 팀 프로젝트를 하면서도, 팀원들의 의견이 다 너무 좋게 들려서 무지성으로 좋아~ 만 외치는 날 볼 수 있었다.
`좋아~`는 저도 자주 들은 것 같네요 😅

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +팀 프로젝트뿐만 아니라, 어떤 모임에서 내가 가장 많이 하는 말이 `좋아~`이다. A의 의견을 들으면 A의 의견이 좋아 보이고, B의 의견을 들으면 B의 의견이 좋아 보인다. 이번 팀 프로젝트를 하면서도, 팀원들의 의견이 다 너무 좋게 들려서 무지성으로 좋아~ 만 외치는 날 볼 수 있었다.
```suggestion
팀 프로젝트뿐만 아니라, 어떤 모임에서 내가 가장 많이 하는 말이 `좋아~`이다. A의 의견을 들으면 A의 의견이 좋아 보이고, B의 의견을 들으면 B의 의견이 좋아 보인다. 이번 팀 프로젝트를 하면서도, 팀원들의 의견이 다 너무 좋게 들려서 무지성으로 좋아~ 만 외쳤었다.
```
로 조금 줄여볼 수 있을 것 같네요 !!!

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +하지만 과연 그 `좋아~`가 과연 팀에게 긍정적인 영향을 미칠까? 라고 질문했을 때, 답은 절대 노!였다. 각자 본인의 생각을 조리 있게 잘 전달하는 팀원들을 보며, 나도 내 의견을 밝혀야겠다고 다짐했다.
```suggestion
하지만 과연 그 `좋아~`가 과연 팀에게 긍정적인 영향을 미칠까? 라고 질문했을 때, 답은 `절대 노!`이다. 각자 본인의 생각을 조리 있게 잘 전달하는 팀원들을 보며, 나도 내 의견을 밝혀야겠다고 다짐했다.
```
`였다`보다는 `이다`가 더 좋아보입니다 :)

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +의식적으로 `좋아~` 만 말하기를 하지 않으려 했다. 시작은 왜 좋은지, 이유를 밝히는 것이었다. `00해서 좋아~` 로 이유를 밝혔다. 다음은 좀 더 내 의견 확실하게 하기였다. A vs B로 서로 대립하는 의견이 충돌했을 때, 둘 다 좋다기보다는 조금이라도 마음 가는 쪽으로 의견을 정했다.
시작은 이라는 의미가 조금 모호하다고 생각돼요!
`요즘은 왜 좋은지 이유를 먼저 밝히고자 한다.` 는 어떤가요 ?! 😊

2022-08-14 09:36 UTC, syoun602 commented on level3.md
> +팀 프로젝트를 하면서 정말 별것도 아닌 일에 자주 웃는다. 누군가 던진 농담에도, PPT 슬라이드 속 애니메이션에도, 하다못해 꼬재가 손바닥을 펼치며 빰!🖐 만 해도 웃는다.
봄 웃음소리가 자주 들려서 저도 기분이 좋습니다 👍

2022-08-14 14:59 UTC, yeon-06 approved these changes
저야말로 봄 덕분에 정말 많이 많이 웃는 것 같아요
남은 기간도 레벨4도 잘 부탁드려용^ㅡ^❤~~~~~~~~

2022-08-14 14:59 UTC, yeon-06 commented on level3.md
> +### 어려운 팀의 목표 찾기, 하지만 없으면 어때~
`어려운 팀 목표 찾기. 없어도 뭐 어때~` 이런 식으로 소제목에서는 `하지만`을 없애는 방향이 더 편하게 읽을 수 있을 것 같아요!
필수는 아니고 어떤 식이 더 좋을지 고려해보시면 좋을 듯 합니다 ㅎㅎㅎ

2022-08-14 14:59 UTC, yeon-06 commented on level3.md
> +레벨2 장바구니 협업 미션 당시에 팀 공동의 목표를 세웠었다. 그리고 ‘공동의 목표 세우기’는 꽤 잘 동작했다. 회의가 산으로 가거나, 어떤 의사결정을 할 때, ‘우리가 하는 말이 목표에 부합하는가?’ 에 대해 고민하고 올바른 길로 나아갔다. 정답이 없는 사안에 대해서도, 공동의 목표를 기준으로 길을 찾아갔다.
썬의 코멘트를 보고 생각해보았는데요
`성공적이었다` 같은 단어는 어떨까요!?

2022-08-14 14:59 UTC, yeon-06 commented on level3.md
> +팀 프로젝트뿐만 아니라, 어떤 모임에서 내가 가장 많이 하는 말이 `좋아~`이다. A의 의견을 들으면 A의 의견이 좋아 보이고, B의 의견을 들으면 B의 의견이 좋아 보인다. 이번 팀 프로젝트를 하면서도, 팀원들의 의견이 다 너무 좋게 들려서 무지성으로 좋아~ 만 외치는 날 볼 수 있었다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 저만 저희 데일리/회의 시간 생각낭나요?
굿~~~~ 이 남발하는 줍줍 회의 타임..ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-08-14 14:59 UTC, yeon-06 commented on level3.md
> +의식적으로 `좋아~` 만 말하기를 하지 않으려 했다. 시작은 왜 좋은지, 이유를 밝히는 것이었다. `00해서 좋아~` 로 이유를 밝혔다. 다음은 좀 더 내 의견 확실하게 하기였다. A vs B로 서로 대립하는 의견이 충돌했을 때, 둘 다 좋다기보다는 조금이라도 마음 가는 쪽으로 의견을 정했다.
좋은 변화네요 👍👍👍

2022-08-14 14:59 UTC, yeon-06 commented on level3.md
> +팀 프로젝트를 하면서 정말 별것도 아닌 일에 자주 웃는다. 누군가 던진 농담에도, PPT 슬라이드 속 애니메이션에도, 하다못해 꼬재가 손바닥을 펼치며 빰!🖐 만 해도 웃는다.
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 🖐

2022-08-14 20:10 UTC, Youngyoon-1 commented on level3.md
> +이번 팀 프로젝트가 나에게 가장 크게 남긴 건 팀원들인 것 같다. 원래 잘 웃는 사람이긴 하지만, 팀원들과 함께 있으면 더 즐겁다. 아주 작은 농담에도 즐겁고, 얼굴만 봐도 웃음이 나온다. 이상한 말과 행동을 해도 웃어주는 팀원들에게 고맙다. 함께 있기만 해도 즐거운 사람들과 남은 스프린트도 즐겁게 마무리하고 싶다.
줍줍에서 얼굴만 봐도 웃음이 나오는 크루가 누군지 궁금하네여

2022-08-15 09:36 UTC, LAH1203 approved these changes
안녕하세요 봄~

저희 글쓰기 조에 유독 줍줍 팀원들이 많네요?! 다들 팀 프로젝트를 하며 좋은 변화를 겪으신 것 같아서 보는 저도 기분이 좋아졌습니다 😊

서로 다른 의견들이 모였지만 그걸 잘 조합해서 하나의 길을 만들어내는 건 팀에서 해내야할 몫이라고 생각해요. 비록 과정을 직접 보지는 못했지만, 이렇게 간접적으로 글로나마 접하니 줍줍 팀은 그 과정을 잘 해내고 있는 것 같네요 👍

남은 기간동안에도 화이팅해서 좋은 사람들과 즐거운 팀 프로젝트 이어가시길 응원하겠습니다~! 봄 화이팅 🙌

2022-08-15 09:36 UTC, LAH1203 commented on level3.md
> +이번 팀 프로젝트가 나에게 가장 크게 남긴 건 팀원들인 것 같다. 원래 잘 웃는 사람이긴 하지만, 팀원들과 함께 있으면 더 즐겁다. 아주 작은 농담에도 즐겁고, 얼굴만 봐도 웃음이 나온다. 이상한 말과 행동을 해도 웃어주는 팀원들에게 고맙다. 함께 있기만 해도 즐거운 사람들과 남은 스프린트도 즐겁게 마무리하고 싶다.
정말 좋은 사람들과 있으면 아무 것도 하지 않아도 웃음이 나오죠 😄

봄이 팀 생활을 하며 좋은 인연들이 생긴 것 같아 글을 읽으면서 저도 기분이 좋아졌습니다 :)

2022-08-15 11:33 UTC, syoun602 approved these changes

2022-08-15 11:55 UTC, JangBomi commented on level3.md
> +레벨2 장바구니 협업 미션 당시에 팀 공동의 목표를 세웠었다. 그리고 ‘공동의 목표 세우기’는 꽤 잘 동작했다. 회의가 산으로 가거나, 어떤 의사결정을 할 때, ‘우리가 하는 말이 목표에 부합하는가?’ 에 대해 고민하고 올바른 길로 나아갔다. 정답이 없는 사안에 대해서도, 공동의 목표를 기준으로 길을 찾아갔다.
좋은 리뷰 감사해요! 성공적이었다 로 수정했습니다!

2022-08-15 11:56 UTC, JangBomi commented on level3.md
> +팀 프로젝트뿐만 아니라, 어떤 모임에서 내가 가장 많이 하는 말이 `좋아~`이다. A의 의견을 들으면 A의 의견이 좋아 보이고, B의 의견을 들으면 B의 의견이 좋아 보인다. 이번 팀 프로젝트를 하면서도, 팀원들의 의견이 다 너무 좋게 들려서 무지성으로 좋아~ 만 외치는 날 볼 수 있었다.
좋아~!~!~!

2022-08-15 11:59 UTC, JangBomi commented on level3.md
> +팀 프로젝트를 하면서 정말 별것도 아닌 일에 자주 웃는다. 누군가 던진 농담에도, PPT 슬라이드 속 애니메이션에도, 하다못해 꼬재가 손바닥을 펼치며 빰!🖐 만 해도 웃는다.
빰~!!

2022-08-15 12:26 UTC, sinb57 approved these changes
안녕하세요 봄!!
레벨1 깃 미션 때도, 레벨2 스프링 빈 토론 미션 때도 뵀는데
이번 글쓰기 미션에도 다시 뵙네요ㅋㅎㅎ 반갑습니다!

봄이 작성해주신 글 잘 봤어요!!
이번 글쓰기 미션 조에 `🐹🐹`팀 세 분과 함께할 수 있어서 좋았는데요!
하나의 팀 프로젝트 속에서 모두 제각각 새로운 점을 깨우치고 발전해나가는 모습이
매우 보기 좋아요! 항상 해맑고 웃는 모습의 `봄`!! 응원합니다~

2022-08-15 12:26 UTC, sinb57 commented on level3.md
> +모든 다름 속에 장바구니 미션 때처럼 딱 정해진 우리 팀의 목표는 세우지 못했다. 하지만 정하지 못한 팀 목표 속에서 우리는 서로의 다름을 인정하고 같은 방향으 나아가고자 했다. 지금 돌아보면, 무조건 팀의 목표를 세워야겠다는 생각은 과한 자신감이었던 것 같다. 이번 팀 프로젝트를 통해, 모두의 생각이 다르더라도 시간이 지나며 충분히 맞춰갈 수 있다는 것
```suggestion
모든 다름 속에 장바구니 미션 때처럼 딱 정해진 우리 팀의 목표는 세우지 못했다. 하지만 정하지 못한 팀 목표 속에서 우리는 서로의 다름을 인정하고 같은 방향으로 나아가고자 했다. 지금 돌아보면, 무조건 팀의 목표를 세워야겠다는 생각은 과한 자신감이었던 것 같다. 이번 팀 프로젝트를 통해, 모두의 생각이 다르더라도 시간이 지나며 충분히 맞춰갈 수 있다는 것을 알았다.
```
오타 발견했습니다!!ㅎ

2022-08-15 12:26 UTC, sinb57 commented on level3.md
> +의식적으로 `좋아~` 만 말하기를 하지 않으려 했다. 요즘은 왜 좋은지 이유를 먼저 밝히고자 했다. `00해서 좋아~` 로 이유를 밝혔다. 다음은 좀 더 내 의견 확실하게 하기였다. A vs B로 서로 대립하는 의견이 충돌했을 때, 둘 다 좋다기보다는 조금이라도 마음 가는 쪽으로 의견을 정했다.
정말 좋은 변화네요!! 마냥 좋다고 하면 듣는 입장에서 이게 정말 좋은건지 의아할 때가 많더라고요ㅜ 지금처럼 `00해서 좋아~` 이유를 밝혀주는 화법은 정말 좋네요ㅎ

2022-08-15 12:56 UTC, JangBomi commented on level3.md
> +모든 다름 속에 장바구니 미션 때처럼 딱 정해진 우리 팀의 목표는 세우지 못했다. 하지만 정하지 못한 팀 목표 속에서 우리는 서로의 다름을 인정하고 같은 방향으 나아가고자 했다. 지금 돌아보면, 무조건 팀의 목표를 세워야겠다는 생각은 과한 자신감이었던 것 같다. 이번 팀 프로젝트를 통해, 모두의 생각이 다르더라도 시간이 지나며 충분히 맞춰갈 수 있다는 것
감사합니다 이프!!

2022-10-04 07:43 UTC, gracefulBrown approved these changes
👍

2022-10-04 07:43 UTC, merged