[레벨3 글쓰기 미션] 우연(전연지) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #316
Opened 2022-08-08 13:37 UTC by ronci

안녕하세요!
레벨 3 글쓰기 초안 리뷰 잘 부탁드립니다!

### [level 3 글](https://github.com/ronci/woowa-writing-4/blob/ronci/level3.md)

열음 @Juhyung990122
코이 @InKyoJeong
빅터 @woose28
알파 @bcc0830
파랑 @summerlunaa

2022-08-15 03:40 UTC, woose28 reviewed
우연 안녕하세요~ 같은 팀원을 글쓰기 미션에서 만나서 더 반갑네요!
팀 문화에 대해서 잘 적어주셔서 공감 가면서 글을 읽었습니다!
간단한 코멘트를 남겼는데 확인 부탁드려요~!
그리고 남은 레벨 3도 같이 힘내보십니다!!

2022-08-15 03:40 UTC, woose28 commented on README.md
> +## Level 3 - ['팀 프로젝트가 나에게 남긴 것'](https://github.com/ronci/woowa-writing-4/blob/ronci/level3.md)
오 README에도 글 목록을 정리해두셨네요!
깔끔하고 좋네요👍 저도 이렇게 정리를 해야겠어요ㅎㅎ

2022-08-15 03:40 UTC, woose28 commented on level3.md
> +남아있는 팀 프로젝트 동안 계속해서 토론하면서 나만의 기준을 생각하고, 나의 의견을 어필해보면서 프로젝트와 함께 나도 성장하고자 한다.
> 남아있는 팀 프로젝트 동안 계속해서 토론하면서 나만의 기준을 생각하고

해당 문장이 `남아있는 팀 프로젝트 기간동안 ~~` 되면 더 자연스러울 거 같아요!

2022-08-15 03:40 UTC, woose28 commented on level3.md
> +스모디 팀에서는 나의 의견을 발언할 기회가 많아서 좋다. 내 의견이 반영되며 커가는 프로젝트를 보면서 프로젝트에 애정이 더 생긴다.
> 내 의견이 반영되며 커가는 프로젝트를 보면서 프로젝트에 애정이 더 생긴다.

맞아요! 서비스에 나의 생각이 담기니 더욱 애정도 생기는 거 같아요ㅎㅎ

2022-08-15 03:40 UTC, woose28 commented on level3.md
> +처음에는 코드 구조도 얘기해보고 컨벤션을 짜고 각자가 원하는 컴포넌트 등 많은 이야기를 나누느라 대부분 시간을 보냈다. 그렇게 처음에 컨벤션을 잘 통일해놓아서 그런지 갈수록 코드의 컨벤션도 잘 맞고 이견 조율 또한 쉬워졌다.
> 처음에 컨벤션을 잘 통일해놓아서 그런지 갈수록 코드의 컨벤션도 잘 맞고 이견 조율 또한 쉬워졌다.

공감 가네요! 4차 스프린트 들어와서 분업 위주로 작업을 하고 있는데, 초기에 잘 맞춘 컨벤션 덕분에 코드 리뷰도 수월하다고 느꼈습니다!

2022-08-15 11:01 UTC, InKyoJeong approved these changes
우연 안녕하세요 코이입니다! 글 잘 읽었어요~
프로젝트 문화 소개와 프로젝트를 하며 느꼈던 것들에 대해 잘 써주신거같아요. 
보면서 공감도 되고 재밌게 읽었습니당 남은 기간도 화이팅!!

2022-08-15 12:11 UTC, bcc0830 requested changes

2022-08-15 12:11 UTC, bcc0830 commented on level3.md
> +억까제도는 자유로운 의견을 내도록 하지만 장점만 말하는 것을 방지하기 위해서 생겼다. 최악의 상황을 가정하여 억지스러운 단점을 말하는 것이다.
정말 뿌듯하네요 ^^

2022-08-15 12:11 UTC, bcc0830 commented on level3.md
> +처음에는 코드 구조도 얘기해보고 컨벤션을 짜고 각자가 원하는 컴포넌트 등 많은 이야기를 나누느라 대부분 시간을 보냈다. 그렇게 처음에 컨벤션을 잘 통일해놓아서 그런지 갈수록 코드의 컨벤션도 잘 맞고 이견 조율 또한 쉬워졌다.
백엔드도 초기에 몹 프로그래밍할 때 컨벤션 맞추느라 시간을 많이 썼는데 비슷했네요

2022-08-15 12:23 UTC, bcc0830 requested changes
우연 안녕하세요
같은 조 알파입니다
같이 레벨 3 무사히 끝내봅시다 파이팅

2022-08-15 13:39 UTC, summerlunaa approved these changes

2022-08-15 13:56 UTC, summerlunaa approved these changes
우연 안녕하세요 파랑입니다!
FE가 세 명인 팀이라 다른 팀들과는 협업이 또 다를 것 같아요ㅎㅎ
억까제도와 열띤 토론으로 팀플을 잘 하고 계시군요!
남은 일주일도 응원합니다 파이팅🔥

2022-08-15 13:56 UTC, summerlunaa commented on level3.md
> +> 나만의 기준을 찾자
나만의 기준을 찾는 게 중요하면서 어려운 것 같아요!

2022-08-15 13:56 UTC, summerlunaa commented on level3.md
> +그리고 유일하게 프론트엔드 3명이 있는 팀에 들어가게 되었다.
FE 3명.. 부럽습니다.. 그래서인지 스모디 퀄리티가..👍

2022-08-15 13:56 UTC, summerlunaa commented on level3.md
> +처음에는 코드 구조도 얘기해보고 컨벤션을 짜고 각자가 원하는 컴포넌트 등 많은 이야기를 나누느라 대부분 시간을 보냈다. 그렇게 처음에 컨벤션을 잘 통일해놓아서 그런지 갈수록 코드의 컨벤션도 잘 맞고 이견 조율 또한 쉬워졌다.
장점만 있는 건 아니군요!

2022-08-15 13:56 UTC, summerlunaa commented on level3.md
> +이러한 팀 문화 때문에 팀에서 의견도 더 편하게 낼 수 있고 안 좋은 점이 있어도 편하게 말할 수 있었다. 또한 내 아이디어라도 좀 더 객관적으로 볼 수 있었다.
억까제도 나쁘지 않네요ㅎㅎ

2022-08-15 14:09 UTC, Juhyung990122 approved these changes
안녕하세요 우연! 만나서 반갑습니다ㅎㅎ
바쁘신데 글쓰기 미션 하시느라 고생많으셨어요.
좋은 문화를 가진 팀에서 일하시면서 함께 성장해나가는 과정이 보여 좋았습니다.
응원과 함께 approve 할게요! 남은 일주일도 파이팅!

2022-08-15 14:09 UTC, Juhyung990122 commented on level3.md
> +스모디 팀에서는 나의 의견을 발언할 기회가 많아서 좋다. 내 의견이 반영되며 커가는 프로젝트를 보면서 프로젝트에 애정이 더 생긴다.
고민과 함께 애정도 더해진다는 것이 공감 되네요ㅎㅎ

2022-08-15 14:47 UTC, ronci commented on README.md
> +## Level 3 - ['팀 프로젝트가 나에게 남긴 것'](https://github.com/ronci/woowa-writing-4/blob/ronci/level3.md)
이렇게 하니까 README에서 확인하기 편하더라구요!

2022-08-15 14:49 UTC, ronci commented on level3.md
> +남아있는 팀 프로젝트 동안 계속해서 토론하면서 나만의 기준을 생각하고, 나의 의견을 어필해보면서 프로젝트와 함께 나도 성장하고자 한다.
좋은 의견이에요! 수정했습니다! [da36198](https://github.com/woowacourse/woowa-writing-4/pull/316/commits/da361987b54204c811bd29f008786e9d0aa4ecab)

2022-08-15 14:49 UTC, ronci commented on level3.md
> +스모디 팀에서는 나의 의견을 발언할 기회가 많아서 좋다. 내 의견이 반영되며 커가는 프로젝트를 보면서 프로젝트에 애정이 더 생긴다.
스모디 최고!

2022-08-15 14:50 UTC, ronci commented on level3.md
> +남아있는 팀 프로젝트 동안 계속해서 토론하면서 나만의 기준을 생각하고, 나의 의견을 어필해보면서 프로젝트와 함께 나도 성장하고자 한다.
함께 자라기! 👍

2022-08-15 14:51 UTC, ronci commented on level3.md
> +억까제도는 자유로운 의견을 내도록 하지만 장점만 말하는 것을 방지하기 위해서 생겼다. 최악의 상황을 가정하여 억지스러운 단점을 말하는 것이다.
ㅋㅋㅋㅋㅋㅋㅋ억까제도 좋은 팀 문화죠

2022-08-15 14:51 UTC, ronci commented on level3.md
> +> 나만의 기준을 찾자
맞아요! 정답이 없어서 더 어려운 것 같더라구요!

2022-08-15 14:52 UTC, ronci commented on level3.md
> +그리고 유일하게 프론트엔드 3명이 있는 팀에 들어가게 되었다.
뿌듯하네요..!

2022-08-15 14:52 UTC, bcc0830 approved these changes

2022-08-15 14:52 UTC, ronci commented on level3.md
> +이러한 팀 문화 때문에 팀에서 의견도 더 편하게 낼 수 있고 안 좋은 점이 있어도 편하게 말할 수 있었다. 또한 내 아이디어라도 좀 더 객관적으로 볼 수 있었다.
생각보다 정말 좋은 팀문화에요!ㅋㅋㅋㅋ

2022-08-15 14:53 UTC, ronci commented on level3.md
> +스모디 팀에서는 나의 의견을 발언할 기회가 많아서 좋다. 내 의견이 반영되며 커가는 프로젝트를 보면서 프로젝트에 애정이 더 생긴다.
스모디에 애정 가득입니다!

2022-08-15 14:59 UTC, woose28 approved these changes

2022-10-04 07:42 UTC, gracefulBrown approved these changes
👍

2022-10-04 07:42 UTC, merged