[레벨 1 글쓰기 미션] 도리(박선호) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #50
Opened 2022-03-28 07:01 UTC by prefer2

안녕하세요 리뷰어님들! 🐠도리🐠라고 합니다
글쓰기는 역시 너무 어렵네요 🥲
우테코 한 달 동안 가장 많이 사용한 말인 `왜?`라는 주재로 글을 써보았습니다!

### [편하게 보기](https://github.com/prefer2/woowa-writing-4/blob/prefer2/level1.md)

@ulimy
@LAH1203
@RIANAEH
@kamwoo
@hyunrrr
@yxxnghwan

피드백 잘 부탁 드립니다 ☺️

2022-03-28 08:53 UTC, cks3066 commented
왜?

2022-03-28 14:10 UTC, soyi47 commented
이제 도리한테 계속 물어볼겁니다. '왜?'

2022-03-29 06:22 UTC, ulimy reviewed
안녕하세요 도리! 백엔드의 아리입니다ㅎㅎ
왜? 라는 질문은 간단하지만 참 많은 생각을 하게 하죠..
공감되는 부분이 많았던 글이었습니다.🥲
제 피드백은 개인의 의견일 뿐, 이 글의 온전한 주인은 도리 뿐이니 전부 반영하지 않으셔도 괜찮습니다!

2022-03-29 06:22 UTC, ulimy commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
어떤 부분은 "우아한 테크 코스"로, 또 어떤 부분은 "우테코" 라고 적혀있어요! 통일해주시면 어떨까요?

2022-03-29 06:22 UTC, ulimy commented on level1.md
> +역으로 나도 '왜?'를 질문할 일이 많아졌다. 아무나 붙잡고 물어봐도 이상하게 보지 않는 환경에 놓이게 되었다. 뭘 그런 걸 궁금해하고 그래 라는 답변이 아니라 함께 답을 찾아가고 자신만의 좋은 답변을 주는 사람들이 많다.
뭘 그런 걸 궁금해하고 그래 라는 답변이 따옴표 등으로 묶여있으면 더 좋을 것 같아요!

2022-03-29 06:22 UTC, ulimy commented on level1.md
> +우아한 테크 코스에 들어오자 나에게 '왜?'를 묻는 사람들이 많아졌다. 페어와 소통할 때나 코드 리뷰를 받을 때 적절한 이유로 그들을 설득해야 한다. 한 달 동안 이 과정에서 말문이 막히거나 머리가 하얘지는 경험을 많이 했다. 무적 답변이었던 '그냥'을 더 이상 사용하지 못하게 되었다. 스스로도 그러게 내가 왜 이렇게 했지? 라는 질문이 많이 들었다.
저도 같은 경험 많이 했습니다ㅠㅠ 공감되네요😂

2022-03-29 07:55 UTC, LAH1203 commented on level1.md
> +## 왜?
왜?

2022-03-29 08:28 UTC, LAH1203 reviewed
안녕하세요 도리~ 하리입니다 😊

도리 글을 읽으면서 많이 공감했어요. 저도 항상 "그냥 다른 사람들이 많이 쓰니까 한다"라는 답변을 많이 하곤 했거든요. 크루들, 리뷰어님과 소통하면서 `내가 왜 이렇게 썼는지`란 질문을 정말 많이 받았는데, 처음엔 대답도 제대로 못하고 머릿속만 하얘졌던 기억이 나네요..🤣

저는 그냥 가볍게 어색한 부분은 없는지를 중점적으로 봤는데요, 워낙 글을 잘 써주셔서 별로 없더라고요ㅎㅎ
이건 어디까지나 제 의견이니 꼭 반영해주지 않으셔도 괜찮아요! 참고만 해주세요 :)

2022-03-29 08:28 UTC, LAH1203 commented on level1.md
> +우아한 테크 코스에 들어오자 나에게 '왜?'를 묻는 사람들이 많아졌다. 페어와 소통할 때나 코드 리뷰를 받을 때 적절한 이유로 그들을 설득해야 한다. 한 달 동안 이 과정에서 말문이 막히거나 머리가 하얘지는 경험을 많이 했다. 무적 답변이었던 '그냥'을 더 이상 사용하지 못하게 되었다. 스스로도 그러게 내가 왜 이렇게 했지? 라는 질문이 많이 들었다.
`스스로도 그러게 내가 왜 이렇게 했지? 라는 질문이 많이 들었다.` 부분을 실제로 읽어봤을 때 살짝 어색한 느낌이 나는 것 같아요. 좀 더 자연스러운 표현으로 바꿔보는건 어떨까요?

예를 들면 다음과 같이 바꿀 수도 있을 것 같아요.

`스스로도 '그러게 내가 왜 이렇게 했지?'라는 의문이 자주 들었다.`

2022-03-29 08:28 UTC, LAH1203 commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
`대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다.`를 글쓰기 규칙에 적혀있는 것처럼 능동형 문장으로 바꿔보면 어떨까요?

```suggestion
우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각한다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사람들이 있다는 것은 정말 신나는 일이다. 다양한 사람들의 의견을 들어보며 나만의 결론을 만들어내는 일이 얼마나 즐거운지 느끼고 있다.
```

2022-03-29 08:28 UTC, LAH1203 commented on level1.md
> +내가 왜 뽑힌 거지? 여러모로 부족함을 많이 느끼고 있다. 기술적으로 뛰어나지도, 그렇다고 다른 면이 뛰어난 것 같지도 않다. 미션을 진행하면 진행할수록 모르는 것으 더 많아지고 공부해야 할 내용은 쌓여만간다. 부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다. 그래도 내가 왜 이 자리에 있게 된 지는 아직 잘 모르겠다. 앞으로 남은 기간 이 질문에
저도 저에게 부족함을 많이 느끼고 있고, 아직도 내가 어떻게 이 교육에 참여를 할 수 있게 된 건지 짐작조차 못하고 있어요 🥲
아마 저희 같은 크루 분들은 더 있을거라 생각해요. 우테코를 하면서 같이 그 답을 찾아갈 수 있으면 좋겠네요 😁

2022-03-29 15:46 UTC, yxxnghwan reviewed
안녕하세요 도리! 백엔드의 알렉스입니다. 글쓰기 미션으로 만나게 돼서 반갑습니다.😁
도리의 글 정말 잘 봤습니다. 도리의 감정과 생각이 잘 드러나있어서 좋았습니다!
전체적으로 글을 너무 잘 써주셔서 간단한 코멘트만 남겼습니다.
앞으로도 파이팅입니다!🔥

2022-03-29 15:46 UTC, yxxnghwan commented on level1.md
> +공부를 하다 보면 '왜?'라는 생각이 들 때가 많다. 우아한 테크 코스에 들어오기 전까지는 시간이 부족하니까, 답을 해줄 사람이 없으니까, 그냥 그렇다고 하니까라는 핑계로 '왜?'에 대한 답을 찾지 않았다. 항상 찜찜한 마음으로 동작만 하면 되지 하고 넘기기 일쑤였다. 이에 관해 묻는 사람은 아무도 없었고 답을 찾는 과정은 많은 노력을 필요하기 때문에 나
많이 공감이 가는 부분이에요🤣

2022-03-29 15:46 UTC, yxxnghwan commented on level1.md
> +이유를 모르는 지식은 금방 휘발된다. 좋은 근거 없이는 상대방을 설득하기 어렵다. 시행착오를 겪으며 이유와 목적을 찾아가고 있다. 스스로를 납득시키고 나니 다른 사람들에게 의견을 말하는 일이 전보다 편해졌다. 좋은 답변을 하기 위해 지금까지 미루어두었던 이유들을 다시 찾는 과정을 밟고 있다.
지나온 것들을 되돌아보며 부족한 점을 채우는 게 쉽지 않을 것 같은데 멋있네요!🔥

2022-03-29 15:46 UTC, yxxnghwan commented on level1.md
> +내가 왜 뽑힌 거지? 여러모로 부족함을 많이 느끼고 있다. 기술적으로 뛰어나지도, 그렇다고 다른 면이 뛰어난 것 같지도 않다. 미션을 진행하면 진행할수록 모르는 것으 더 많아지고 공부해야 할 내용은 쌓여만간다. 부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다. 그래도 내가 왜 이 자리에 있게 된 지는 아직 잘 모르겠다. 앞으로 남은 기간 이 질문에
`미션을 진행하면 진행할수록 모르는 것으 더 많아지고` 오타 확인 부탁드려요!
`내가 왜 뽑힌 거지?` 하는 부분은 따옴표로 감싸는게 어떨까요?!

2022-03-29 16:48 UTC, hyunrrr commented
도리 안녕하세요!!! 같은 글 쓰기 팀 조시입니다!! 잘부탁드려요~~!
글 잘 읽었습니다!! 마법의 단어 “왜?” 우아한테크코스에서 만큼은 정말 좋은 단어인거 같습니다! 저도 미션을 진행하면서 왜 이렇게 해야하지?를 많이 생각한거 같네요!!
“부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다” 너무 멋지십니다!!
언젠가는 부족함이 하나도 없어 원동력이 0이되는 날이 오기를 응원하겠습니다!!

2022-03-29 16:49 UTC, hyunrrr commented on level1.md
> +우아한 테크 코스에 들어오자 나에게 '왜?'를 묻는 사람들이 많아졌다. 페어와 소통할 때나 코드 리뷰를 받을 때 적절한 이유로 그들을 설득해야 한다. 한 달 동안 이 과정에서 말문이 막히거나 머리가 하얘지는 경험을 많이 했다. 무적 답변이었던 '그냥'을 더 이상 사용하지 못하게 되었다. 스스로도 그러게 내가 왜 이렇게 했지? 라는 질문이 많이 들었다.
라는 질문이 많이 들었다. -> 라는 질문을 많이 했다.
(개인적으로 ‘이’가 연속으로 반복되는게 조금 어색하다고 느꼈습니다!!)

2022-03-29 16:49 UTC, hyunrrr commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
큰 장점 중 하나라고 생각이 된다 -> 큰 장점 중 하나라고 생각이 든다
(내가 주어이니 된다 보다는 든다가 자연스럽다고 느꼈습니다!!)

2022-03-29 16:50 UTC, hyunrrr commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
얼마나 즐거운지 느끼고 있다. -> 얼마나 즐거운지 느낀다.
(저는 개인적으로 주어가 ‘나’일때 ‘느끼고 있다’라는 표현이 어색한거 같아요!! ‘느낀다’는 어떠신가요?!)

2022-03-29 16:50 UTC, hyunrrr commented on level1.md
> +내가 왜 뽑힌 거지? 여러모로 부족함을 많이 느끼고 있다. 기술적으로 뛰어나지도, 그렇다고 다른 면이 뛰어난 것 같지도 않다. 미션을 진행하면 진행할수록 모르는 것으 더 많아지고 공부해야 할 내용은 쌓여만간다. 부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다. 그래도 내가 왜 이 자리에 있게 된 지는 아직 잘 모르겠다. 앞으로 남은 기간 이 질문에
부족함을 많이 느끼고 있다. -> 부족함을 많이 느낀다.

2022-03-30 12:11 UTC, kamwoo commented
안녕하세요 도리! 같은 조 밧드입니다 🙂
왜? 라는 주제를 시작으로 이야기를 잘 풀어내 주셨다고 생각이 들었습니다!
읽으면서 우테코 교육과정을 잘 보내고 계신걸 느낄 수 있었습니다.

2022-03-31 06:27 UTC, RIANAEH reviewed
안녕하세요 도리!! (니모의 도리라니 너무 귀여운 닉네임이네요😆)
이렇게 프론트 크루를 만나게 돼서 너무 반가워요!!

글이 전체적으로 "왜?"라는 주제에 잘 부합해서 술술 읽힌 것 같아요!! 💯
이미 다른 크루분들이 리뷰를 잘 남겨주셔서 하나 정도만 간단히 남겨봤어요!!
앞으로도 같이 파이팅해요~😎

2022-03-31 06:27 UTC, RIANAEH commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
```suggestion
우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변을 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사람들이 있다는 것은 정말 신나는 일이다. 다양한 사람들의 의견을 들어보며 나만의 결론을 만들어내는 일이 얼마나 즐거운지 느끼고 있다.
```
"답변 준다"가 읽는 데 어색하게 느껴지더라구요!! 혹시 이렇게 변경해보면 어떨까요??

2022-03-31 06:27 UTC, RIANAEH commented on level1.md
> +내가 왜 뽑힌 거지? 여러모로 부족함을 많이 느끼고 있다. 기술적으로 뛰어나지도, 그렇다고 다른 면이 뛰어난 것 같지도 않다. 미션을 진행하면 진행할수록 모르는 것으 더 많아지고 공부해야 할 내용은 쌓여만간다. 부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다. 그래도 내가 왜 이 자리에 있게 된 지는 아직 잘 모르겠다. 앞으로 남은 기간 이 질문에
많이 공감가는 내용이네요. 
저도 레벨 1의 막바지에 들어서니 성장한 부분도 많지만 점점 더 공부할 내용들이 쌓여가면서 부족한 점이 더 많이 보이게 되더라구요. 
앞으로 더 성장할 수 있는 부분이 많다는 것이니 "오히려 좋아!!"라고 긍정적으로 생각하고 있습니다!!
앞으로 우테코 생활동안 같이 성장해요 도리!! 😄

2022-04-03 05:20 UTC, prefer2 commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
저도 모르게 섞어 쓰고 있었네요! 감사합니다

2022-04-03 05:20 UTC, prefer2 commented on level1.md
> +## 왜?
왜?

2022-04-03 05:22 UTC, prefer2 commented on level1.md
> +우아한 테크 코스에 들어오자 나에게 '왜?'를 묻는 사람들이 많아졌다. 페어와 소통할 때나 코드 리뷰를 받을 때 적절한 이유로 그들을 설득해야 한다. 한 달 동안 이 과정에서 말문이 막히거나 머리가 하얘지는 경험을 많이 했다. 무적 답변이었던 '그냥'을 더 이상 사용하지 못하게 되었다. 스스로도 그러게 내가 왜 이렇게 했지? 라는 질문이 많이 들었다.
와 이렇게 바꾸니까 훨씬 더 잘 읽히네요! 감사합니다 하리~~

2022-04-03 05:24 UTC, prefer2 commented on level1.md
> +내가 왜 뽑힌 거지? 여러모로 부족함을 많이 느끼고 있다. 기술적으로 뛰어나지도, 그렇다고 다른 면이 뛰어난 것 같지도 않다. 미션을 진행하면 진행할수록 모르는 것으 더 많아지고 공부해야 할 내용은 쌓여만간다. 부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다. 그래도 내가 왜 이 자리에 있게 된 지는 아직 잘 모르겠다. 앞으로 남은 기간 이 질문에
오타를 체크한다고 했는데도 있네요! 감사합니다 알렉스~~

2022-04-03 05:28 UTC, prefer2 commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
오 좋네요! 훨씬 자연스러워졌네요~~

2022-04-03 05:29 UTC, prefer2 commented on level1.md
> +우테코 사람들은 조금만 용기를 내면 누구보다도 열정적으로 답변 준다. 게더에 지나다니는 아무나 붙잡고 궁금한 점을 물어보면 된다. 페어에게도 궁금한 점이 있으면 그냥 물어보고는 한다. 대면에 비해 부끄러움이 덜하다는 것, 비대면 교육의 큰 장점 중 하나라고 생각이 된다. 이런 것도 물어봐도 될까? 라는 고민을 많이 안하게 되었다. 궁금한 점을 해결해줄 사
오 그렇네요! 조사를 붙이는게 훨씬 잘 읽히네요. 수정했습니다!

2022-04-03 10:41 UTC, kamwoo requested changes
request changes눌러야 되는걸 이제 알았습니다 😭

2022-04-04 00:51 UTC, LAH1203 approved these changes
🐠'왜?'에 대한 답을 찾아가는 멋진 도리🐠 안녕하세요 하리입니다~ 한 주만에 다시 찾아왔습니다 🤭

> 무적 답변이었던 '그냥'을 더 이상 사용하지 못하게 되었다. 스스로도 '그러게 내가 왜 이렇게 했지?'라는 의문이 자주 들었다.

저도 누군가 이유를 물어보면 '그냥'이라는 답변을 많이 했었는데, 우테코에서는 그게 통하지 않으니 처음에 페어 프로그래밍을 하거나 리뷰를 받을 때도 많이 어려워했던 기억이 나네요 🥲 저는 그럴 때 '이걸 어떻게 대답하면 괜찮을까?'하는 걱정부터 했었는데, '내가 왜 이렇게 했지?'라고 의문을 가졌던 도리가 대단하고 멋있게 느껴지네요.. 그러니까 오프라인으로 만나게 되면 꼭 티라미수 먹으러 가시죠 ㅎㅎㅎ 😆

> 이유를 모르는 지식은 금방 휘발된다. 좋은 근거 없이는 상대방을 설득하기 어렵다. 좋은 답변을 하기 위해 지금까지 미루어두었던 이유들을 다시 찾는 과정을 밟고 있다.

도리의 글은 한 달동안 도리의 생각 변화를 느낄 수 있어서 너무 좋았어요~ `좋은 답변을 하기 위해 지금까지 미루어두었던 이유들을 다시 찾는 과정을 밟고 있다.` 크..

> 부족함을 원동력으로 사는 사람이라 크게 조급하지는 않다.

도리는 오히려 부족함을 원동력으로 사는 사람이라고 해주셔서 살짝 부러웠습니다.. 정말 멋지고 좋은 마인드라고 생각해요! 저도 그렇게 되려고 노력해봐야겠어요 😉

사실 이 글과 여태까지 도리가 어떻게 해왔는지 보면서 저는 도리가 왜 우테코에 뽑혔는지 조금 짐작은 가지만, 답은 스스로 찾아가야 의미가 있는거니까 저는 말하지 않겠습니다 🤫 하지만 곧 스스로 깨달으실 것 같아요~!

글쓰기 하시느라 정말 수고 많으셨습니다~ 나중에 게더에서 '왜?'를 물어보러 가겠습니다 🥳

2022-04-04 02:34 UTC, RIANAEH approved these changes
도리!! 수정사항 확인했습니다~
글이 더 읽기 좋아졌네요💯
`왜?`라는 주제로 정말 통일감 있는 글이어서 너무 좋았습니다😎
[동방신기(TVXQ)의 '왜 (Keep Your Head Down)'](https://www.youtube.com/watch?v=djJb5iSL0Do)를 추천드리며 물러나보겠습니다~^^~

2022-04-04 03:53 UTC, kamwoo approved these changes
안녕하세요 도리!
도리의 글을 읽으면 우테노 과정을 정말 잘보내고 계신게 느껴졌어요.
남은 기간 동안 본인에게 던진 질문에 답을 찾으셨으면 좋겠어요!🙂  approve하겠습니다!

2022-04-04 07:12 UTC, yxxnghwan commented
안녕하세요, 도리🤗
이번 글쓰기 미션 수행하느라 고생 많으셨어요!
저도 우테코를 하면서 `왜?`라는 질문에 대답하려다 많은 성장의 기회를 받은 것 같아서 전체적으로 공감가는 내용의 글이네요!
도리가 자신만의 결론을 만들어가면서 즐거운 레벨1을 보냈기 바랍니다!
다음 레벨도 파이팅이에요!🔥

2022-04-04 07:12 UTC, yxxnghwan approved these changes
안녕하세요, 도리🤗
이번 글쓰기 미션 수행하느라 고생 많으셨어요!
저도 우테코를 하면서 왜?라는 질문에 대답하려다 많은 성장의 기회를 받은 것 같아서 전체적으로 공감가는 내용의 글이네요!
도리가 자신만의 결론을 만들어가면서 즐거운 레벨1을 보냈기 바랍니다!
다음 레벨도 파이팅이에요!🔥

2022-04-04 08:03 UTC, ulimy approved these changes
안녕하세요 도리! 아리입니다~!
피드백 반영 해주신 것 너무 잘 봤습니다!
비록 글쓰기 미션은 여기서 마무리 되지만 앞으로 좋은 친구로 함께 성장해나갔으면 좋겠어요:) 저와 새롭게 인연을 맺어주셔서 감사합니다. 또 뵈어요!

2022-04-22 09:03 UTC, woowapark commented
도리 안녕하세요! 
도리한테는 오히려 온라인이어서 좋은 레벨1이었군요ㅋㅋ '왜'를 끝까지 물어보고 정리하는 과정이 쉽지만은 않겠지만..! 우테코에서는 함께하는 크루들이 많으니 조금은 더 즐거움을 느끼면서 도리의 '왜'를 찾아가실 수 있을 거라고 생각해봅니다ㅎㅎ 레벨2에서도 질문왕 도리가 되어주시길 응원할게요!
(tmi: 우테코는 붙여서 씁니다!ㅋㅋ 우아한테크코스~)

2022-04-22 09:03 UTC, merged