[레벨 1 글쓰기 미션] 우연(전연지) 미션 제출합니다.
woowacourse/woowa-writing-4 pull request #69
Opened 2022-03-28 09:07 UTC by ronci

레벨 1 글쓰기 초안 리뷰 잘 부탁드립니다!

2022-03-28 12:31 UTC, jayjaehunchoi requested changes
안녕하세요 우연! 후니에요!

프론트엔드 크루인 우연을 많이 마주치지 못해 아쉽네요 ㅠㅠ
우연은 이런 고민을 갖고 계셨군요!! 글 정말 잘 읽었어요

전체적으로 1인칭 주어를 제거할 방법을 고민하면 더 좋은 글이 될 것 같아요!!
몇가 지 수정하면 좋을 것 같은 내용을 남겼는데 참고하시어 반영 or 반려해주세요!

앞으로 많이 이야기나눠요 게더에서 우연 계실 때 한 번 인사갈게요 !

2022-03-28 12:31 UTC, jayjaehunchoi commented on level1.md
> +나는 내 인생의 낙 중 하나였던 게임을 끊었고 미션에 집중했다. 남들이 기본으로 아는 것을 나는 찾아서 공부했다. 남들은 짧은 시간에 짜는 코드를 나는 몇 시간을 들여서 코드를 짰다. 크루원들은 다른 크루들의 미션 PR을 보며 배우고 스터디를 할 때, 나는 내 미션 기능을 구현하고 피드백 수정하기에 급급했다.
`나는 내` -> 나는 or 내 만 적어도 좋을 것 같아요!

2022-03-28 12:31 UTC, jayjaehunchoi commented on level1.md
> +마침 휴학을 고민 중인 나에게는 정말 좋은 선택지였다.
```suggestion
마침 휴학을 고민 중인 찰나에 우테코는 정말 좋은 선택지였다.
```

2022-03-28 12:31 UTC, jayjaehunchoi commented on level1.md
> +내가 필요했던 기술들이 우테코 교육과정에 모두 있었다.
```suggestion
배우고 싶은 모든 기술들이 우테코 교육과정에 포함되어 있었다.
```

요렇게 1인칭 주어를 제거해보는 것도 좋을 것 같아요

2022-03-29 08:47 UTC, Gyuchool reviewed
안녕하세요 우연!
기론입니다 예전에 깃(?)실습할 때, 뵀던 것 같네요 ㅎㅎ
글을 너무 잘 적어주셔서 읽는데 불편함이 없었어요!
리뷰 할게 없어 보였는데, 굳이 리뷰를 해야 한다면 한 가지 정도 커멘트로 남겼습니다!

2022-03-29 08:47 UTC, Gyuchool commented on level1.md
> +나는 내 인생의 낙 중 하나였던 게임을 끊었고 미션에 집중했다. 남들이 기본으로 아는 것을 나는 찾아서 공부했다. 남들은 짧은 시간에 짜는 코드를 나는 몇 시간을 들여서 코드를 짰다. 크루원들은 다른 크루들의 미션 PR을 보며 배우고 스터디를 할 때, 나는 내 미션 기능을 구현하고 피드백 수정하기에 급급했다.
> 나는 내 인생의 낙 중 하나였던 게임을 끊었고 미션에 집중했다.

게임을 끊었다니.. 대단하시네요.
저도 본 받아서 끊도록 노력해보겠읍니다.

2022-03-29 08:47 UTC, Gyuchool commented on level1.md
> +3학년 여름학기가 되자마자 어떤 분야가 있을지 궁금하기도 하고 미리 공부해보고 싶어서 알아보았다.
어떤 분야가 무엇을 뜻할까요? 
코딩에 어떤 분야가 있을 지인가요? 어떤 진로가 있을 지를 뜻한 걸까요?
좀 더 구체적이면 좋을 것 같아요!

2022-03-30 07:17 UTC, yeon-06 commented on level1.md
> +대학교를 졸업하고 취업하고 싶었다.
대학교 졸업 하자마자 칼취업을 하고 싶었다는 의미셨을까요 ?_?
대학교를 졸업하는 이야기 다음에 3학년 이야기가 나와서 헷갈릴 수 있을 것 같아요
바로 다음 문장이랑 더 매끄럽게 이어지면 좋을 것 같아요 😄

2022-03-30 07:21 UTC, yeon-06 commented on level1.md
> +프론트엔드를 어떻게 공부할까에 대한 고민은 우아한테크코스를 알고 해결되었다.<br>
조금 더 풀어서 써주시면 더 좋을 것 같아요!
프론트를 선택한 과정에 대해서는 자세히 써있는데 고민은 후다닥 지나가는 느낌이 드네요😂
우테코를 알게 되기 전까지 많은 고민을 하셨을 것이고 짧든 길든 그걸 표현해주셔도 좋을 것 같아요 👍

```suggestion
개발 분야를 정했는데 프론트엔드를 어떻게 공부할지 막막해졌다.  
이 고민은 우아한테크코스를 알게 되며 해결되었다.<br>
```

2022-03-30 07:23 UTC, yeon-06 commented on level1.md
> +사실 지금도 누군가 내게 '너는 우테코에 어떻게 들어갔어?'라고 물어본다면 '글쎄…?'라고밖에 말하지 못할 것 같다. 하지만 이제는 '내 성장의 가능성을 본 거 아닐까'라고 웃으며 말할 수 있지 않을까 하고 혼자 생각해본다.
코치님들도 하시는 말씀이지만 자신을 못 믿겠다면 코치들의 사람 보는 눈을 믿어봅시다 😎
제가 보기엔 우연도 많은 고민과 생각을 하시고 자신만의 정의와 결정도 내리신 것 같아요
앞으로의 우테코 생활도 잘 하실게 눈에 훤히 보입니다ㅋㅋㅋ

2022-04-01 08:28 UTC, gudonghee2000 commented
안녕하세요 우연!
글이 정말 잘 읽혔어요!
저도 비슷한 고민을 가졌어서 많은 부분 공감이 되네요ㅎㅎ

2022-04-01 08:29 UTC, gudonghee2000 commented on level1.md
> +아무것도 모르는 상태였기 때문에 남들에 비해 느렸고 더 열심히 해야 했다.
저는 자바를 공부하고 있지만 공감이 되는군요😊

2022-04-01 08:32 UTC, gudonghee2000 commented on level1.md
> +
포코와의 면담에서 고민이 해결됫던 일화를 얘기해주시면 글에 더욱 몰입할 수 있을거 같아요!

2022-04-03 14:49 UTC, leo0842 commented
안녕하세요 우연! 처음 뵙기도 하고 분야도 다르지만 공감가는 이야기가 정말 많아서 재밌게 읽었습니다!

`3기분들이 해 주셨던 강의 중 '잘하는 사람을 잘 무시하는 법'` 저도 이 특강이 가장 기억에 남았고 이 특강 이후로 자신감을 가지게 된 것 같아요.

글의 흐름이 두 번째 페이지를 기대하게 만들게 되네요! 잘 읽었습니다 ㅎㅎ

2022-04-04 06:49 UTC, ronci commented on level1.md
> +나는 내 인생의 낙 중 하나였던 게임을 끊었고 미션에 집중했다. 남들이 기본으로 아는 것을 나는 찾아서 공부했다. 남들은 짧은 시간에 짜는 코드를 나는 몇 시간을 들여서 코드를 짰다. 크루원들은 다른 크루들의 미션 PR을 보며 배우고 스터디를 할 때, 나는 내 미션 기능을 구현하고 피드백 수정하기에 급급했다.
둘 다 지우는 방향으로 수정했습니다!

2022-04-04 06:59 UTC, ronci commented on level1.md
> +3학년 여름학기가 되자마자 어떤 분야가 있을지 궁금하기도 하고 미리 공부해보고 싶어서 알아보았다.
```
3학년 여름학기가 되자마자, 프로그래머도 중에서도 어떤 다양한 직업이 있을지 궁금했다.
그리고 직업에 대한 관련 지식을 미리 공부해보고 싶어서 관련 직업들을 알아보았다.
찾아본 직업들 중, 내 흥미를 사로잡은 것은 프론트엔드였다.
```
다음과 같이 수정해보았습니다! 괜찮을까요??

2022-04-04 07:07 UTC, ronci commented on level1.md
> +대학교를 졸업하고 취업하고 싶었다.
맞습니다!
이야기가 좀 더 이어지도록 수정해보았습니다!

2022-04-04 07:09 UTC, ronci commented on level1.md
> +내가 필요했던 기술들이 우테코 교육과정에 모두 있었다.
무의식적으로 제가 1인칭 주어를 많이 썼네요! 좋은 의견 감사합니다!

2022-04-04 07:11 UTC, ronci commented on level1.md
> +프론트엔드를 어떻게 공부할까에 대한 고민은 우아한테크코스를 알고 해결되었다.<br>
좋은 의견감사합니다! 수정했습니다!

2022-04-04 07:12 UTC, ronci commented on level1.md
> +나는 내 인생의 낙 중 하나였던 게임을 끊었고 미션에 집중했다. 남들이 기본으로 아는 것을 나는 찾아서 공부했다. 남들은 짧은 시간에 짜는 코드를 나는 몇 시간을 들여서 코드를 짰다. 크루원들은 다른 크루들의 미션 PR을 보며 배우고 스터디를 할 때, 나는 내 미션 기능을 구현하고 피드백 수정하기에 급급했다.
게임의 즐거움을 우테코에서의 즐거움으로 대체하고 있는 것 같습니다!ㅎㅎㅎㅎ

2022-04-04 07:12 UTC, ronci commented on level1.md
> +사실 지금도 누군가 내게 '너는 우테코에 어떻게 들어갔어?'라고 물어본다면 '글쎄…?'라고밖에 말하지 못할 것 같다. 하지만 이제는 '내 성장의 가능성을 본 거 아닐까'라고 웃으며 말할 수 있지 않을까 하고 혼자 생각해본다.
ㅋㅋㅋㅋㅋㅋ그렇게 말씀해주셔서 감사합니다!
코치님들의 눈... 믿습니다..!!!

2022-04-04 07:27 UTC, ronci commented on level1.md
> +
수정했습니다!!

2022-04-04 07:35 UTC, jayjaehunchoi approved these changes

2022-04-04 09:16 UTC, gudonghee2000 approved these changes
안녕하세요 우연! 

> 포코에게 고민을 털어놓았을 때, 포코는 목표도 정해보고 잘하는 사람에게 많이 배워보라고 조언해주셨다. 그 말을 듣고 우테코에서의 나의 목표는 무엇인지 계속 고민해보았다.

포코에게 고민을 털어 놓았던 구체적인 장면을 적어주셨군요!
저는 우연이 포코와 대화하시는 모습이 상상되어서 좋았어요!!

> 게더에서 포코에게 고민을 털어놓았을 때, 포코는 "우테코를 하면서 이뤄내고 싶은 목표를 정해보는건 어떨까요?"라고 조언해주셨다. 상담이 끝나고 침대에 누워 포코가 해주신 말씀을 떠올리며 "우테코 기간 동안 나의 목표는 뭘까?"에 대해 고민해보았다. 

저는 글을 잘 모르지만 일화에 대화하는 듯한 내용을 넣어주면 구체적인 장면이 더욱 상상되지 않을까 해서 적어보았어요!
글이 잘 읽히고 많은 부분 공감되어서 좋았어요 우연!

approve 드렸습니다!
좋은 글 잘 읽었습니다😊

2022-04-04 10:22 UTC, yeon-06 approved these changes

2022-04-04 10:54 UTC, Gyuchool approved these changes
원래 멋있었던 우연의 글이 피드백들 더해지고 더 멋있어졌네요! 
앞으로 함께 성장해요~!

2022-04-15 01:53 UTC, seokhongkim approved these changes
우연, 안녕하세요.
다른 크루들과 비교하지 않고, 본인의 성장에 집중하기로 한 것 좋네요.
우테코 과정에서 우연의 목표를 성취하고, 성장하는 모습을 기대합니다. 👍

2022-04-15 01:53 UTC, merged